Variant-4
frontend-park-mail-ru/homework_2021_1 pull request #2
Opened 2021-02-06 13:18 UTC by Tullerpeton

Здравствуйте. Прошу Вас проверить моё дз0.

С уважением
Суворов Никита (АПО-22)

2021-02-06 16:26 UTC, Betchika99 requested changes
Приветствую тебя на курсе фронтенда! Впереди тебя ждут классный семестр, очень плодотворная работа и (я уверена) классный продукт в портфолио. Заранее желаю тебе удачи :) 
Ты отлично справился с дз0, но есть некоторые замечания и вопросы к твоему решению. Я думаю, ты легко с ними справишься и быстро получишь свои заветные баллы. Если возникнут какие-то сложности, можешь смело писать мне в телеграмм @emdobryanskaya

1) Основную задачу твоя функция решает хорошо, но что будет, если в нее передадут кривые параметры? Давай добавим в функцию валидацию, а также напишем негативные тесты, которые будут проверять это
2) Добавленный тест не очень информативный. Он не дает какой-то исчерпывающей информации по поводу работы функции. Необходимо добавить более информативные тесты, как на позитивные, так и на негативные случаи работы функции
3) Для удобного использования JS-функций разработчики пишут к своим функциям небольшую документацию прямо в коде. Добавь JSDoc (подробнее можешь почитать про нее [здесь](https://jsdoc.app/about-getting-started.html))
4) Ты использовал стандартные функции работы с массивами. Это очень круто. Но как бы ты решил эту задачу, если бы их не было в языке?

2021-02-06 16:26 UTC, Betchika99 commented on source/inverse.js
> +	let slc1 = array.slice(0, num),
неизменяемые переменные лучше всего обозначать через `const`, чтобы семантически было корректно. Почитать про отличия ключевых слов можно [здесь](https://learn.javascript.ru/variables), а если ты уже достаточно разобрался, можешь обратиться [к этому материалу](https://learn.javascript.ru/var), чтобы узнать некоторые тонкости

2021-02-06 16:26 UTC, Betchika99 commented on source/inverse.js
> +	let slc1 = array.slice(0, num),
давай будем называть переменные более однозначно. Название переменной должно однозначно говорить разработчику о ее назначении. Поэтому неоднозначные (например, `a`) и сокращенные названия не приветствуются

2021-02-06 16:26 UTC, Betchika99 commented on source/inverse.js
> +	return (num >= 0) ? [...slc1, ...slc2.reverse()] : [...slc1.reverse(), ...slc2];
круто, что ты нашел такой способ инвертирования массива, как reverse. Но у него есть одна важная особенность, которая очень сильно может попортить жизнь разработчику, который будет использовать твою функцию inverse. Расскажешь, какая? :) 
P.S. за подробностями [сюда](https://learn.javascript.ru/array-methods), там все описано

2021-02-06 16:26 UTC, Betchika99 commented on source/inverse.js
> +	return (num >= 0) ? [...slc1, ...slc2.reverse()] : [...slc1.reverse(), ...slc2];
расскажи, что делает оператор "..." и зачем он здесь нужен?

2021-02-06 16:26 UTC, Betchika99 commented on tests/inverse.js
> +		assert.deepEqual(inverse([ null, true,-Infinity, '' ]), [ '', -Infinity, true, null ]);
пробельчик потерялся. Учись работать глазами, как линтер :)

2021-02-06 16:26 UTC, Betchika99 commented on tests/inverse.js
> +		assert.deepEqual(inverse([ Infinity, -Infinity ]), [ -Infinity, Infinity ]);
здесь можно добавить условия, когда ты все таки передаешь какое-то число вторым аргументом в функцию `inverse`

2021-02-06 16:26 UTC, Betchika99 commented on tests/inverse.js
> +	QUnit.test('Функция работает с массивом чётной длины', function (assert) {
что проверяет этот тест? какой случай использования функции? грубо говоря, зачем он нужен?

2021-02-06 20:25 UTC, Tullerpeton commented on source/inverse.js
> +const inverse = (array, num = 0) => {
Можно было бы использовать ключевое слово `function`.
```js
function inverse(array, num = 0)  {
..........
}
```

2021-02-06 23:32 UTC, Betchika99 commented on source/inverse.js
> +const inverse = (array, num = 0) => {
👍

2021-02-06 23:37 UTC, Tullerpeton commented
1. Добавил проверку на валидность входных данных. Если в функцию приходят некорректные данные, то бросаю исключение.
2. Убрал бессмысленные тесты и добавил негативные.
3. Добавил JSDoc для функции.
4. Функция `inverse` без использования стандартных фукций для работы с массивом:
```js
'use strict'

const inverse = (array, num = 0) => {
	if (!Array.isArray(array) || !Number.isInteger(num))
		throw new TypeError('Incorrect input data');

	let leftBorder = 0, rightBorder = array.length - 1;
	if (num > 0){
		leftBorder += num;
	} else {
		rightBorder += num;
	}

	let reversedArray = array;
	let buff;
	for (; leftBorder < rightBorder; leftBorder++, rightBorder--) {
		buff = reversedArray[leftBorder];
		reversedArray[leftBorder] = reversedArray[rightBorder];
		reversedArray[rightBorder] = buff;
	}

	return reversedArray;
}

```

2021-02-06 23:38 UTC, Tullerpeton commented on source/inverse.js
> +	let slc1 = array.slice(0, num),
1. Переименовал переменные `slc1`, `slc2`-> `slice1`, `slice2`
2. Заменил `let` на `const`, поскольку меняется только содержимое массива, а не сам указатель.

2021-02-06 23:38 UTC, Tullerpeton commented on source/inverse.js
> +	return (num >= 0) ? [...slc1, ...slc2.reverse()] : [...slc1.reverse(), ...slc2];
1. `reverse()` изменяет исходный массив и возвращает его. Изменение исходного массива может быть неожиданным поведением данной функции.
2. Оператор `...` распаковывает массив и мы получаем все его элементы. Иначе получился бы массив массивов. Так же можно было бы использовать
`array1.concat(array2)`

2021-02-06 23:41 UTC, Tullerpeton commented on tests/inverse.js
> +	QUnit.test('Функция работает с массивом чётной длины', function (assert) {
Избыточный тест - удалил. Изначально написал его для реализации фунции `inverse()`, в которой не использовал стандартные функции по работе с массивом.

2021-02-07 18:03 UTC, Tullerpeton commented on tests/inverse.js
> +		assert.deepEqual(inverse([ Infinity, -Infinity ]), [ -Infinity, Infinity ]);
Добавил тест: 
`inverse([1], 1)`

2021-02-07 21:59 UTC, Betchika99 requested changes
уже очень хорошо. Сделай крайние правки и задание будет принято :)

2021-02-07 21:59 UTC, Betchika99 commented on source/inverse.js
> +	if (!Array.isArray(array) || !Number.isInteger(num))
давай придерживаться код-стайла в js и обернем блок оператора if в фигурные скобки. Подробнее про код стайл почитай [вот здесь](https://learn.javascript.ru/coding-style), это полезно))

2021-02-07 22:01 UTC, Betchika99 commented on source/inverse.js
> +	return (num >= 0) ? [...slc1, ...slc2.reverse()] : [...slc1.reverse(), ...slc2];
как можно было бы сделать функцию чистой? т.е. как можно заменить `reverse`?

2021-02-07 22:10 UTC, Betchika99 commented
> 1. Добавил проверку на валидность входных данных. Если в функцию приходят некорректные данные, то бросаю исключение.
> 2. Убрал бессмысленные тесты и добавил негативные.
> 3. Добавил JSDoc для функции.
> 4. Функция `inverse` без использования стандартных фукций для работы с массивом:
> 
> ```js
> 'use strict'
> 
> const inverse = (array, num = 0) => {
> 	if (!Array.isArray(array) || !Number.isInteger(num))
> 		throw new TypeError('Incorrect input data');
> 
> 	let leftBorder = 0, rightBorder = array.length - 1;
> 	if (num > 0){
> 		leftBorder += num;
> 	} else {
> 		rightBorder += num;
> 	}
> 
> 	let reversedArray = array;
> 	let buff;
> 	for (; leftBorder < rightBorder; leftBorder++, rightBorder--) {
> 		buff = reversedArray[leftBorder];
> 		reversedArray[leftBorder] = reversedArray[rightBorder];
> 		reversedArray[rightBorder] = buff;
> 	}
> 
> 	return reversedArray;
> }
> ```

молодец! теперь ты видишь, насколько красивы встроенные в JS функции и насколько они упрощают жизнь разработчикам :) Есть один нюанс в такой реализации - ты присваиваешь массив в массив. В JS это означает, что присваивается ссылка. Поэтому здесь могут возникнуть проблемы. Обрати на это внимание и в следующих фрагментах кода не допускай такой ошибки

2021-02-08 11:07 UTC, Tullerpeton commented on source/inverse.js
> +* Changes the order of the elements in the massic to the opposite.
Заменил на `array`

2021-02-08 11:08 UTC, Tullerpeton commented on source/inverse.js
> +* @param {Integer} num A number of elements to skip. If the number is
Использовал тип `number`, поскольку он представляет как целочисленные значения, так и числа с плавающей точкой

2021-02-08 11:08 UTC, Tullerpeton commented on source/inverse.js
> +* @param {Array} array An array of elements
Тогда нужно писать `object`, если массив не относится к базовым типам? Просто я смотрел примеры в [документации JSDoc](https://jsdoc.app/tags-type.html) и там использовали `Array.<type>`. Но поскольку здесь массив может содержать элементы любого типа, то я написал `Array.<*>`

2021-02-08 11:08 UTC, Tullerpeton commented on source/inverse.js
> +* minmax([1, 2, 3, 4, 5]);
Использовал примеры из документации и не поменял

2021-02-08 11:09 UTC, Tullerpeton commented on source/inverse.js
> +	if (!Array.isArray(array) || !Number.isInteger(num))
Добавил фигурные скобки

2021-02-08 11:28 UTC, Tullerpeton commented on source/inverse.js
> +	return (num >= 0) ? [...slc1, ...slc2.reverse()] : [...slc1.reverse(), ...slc2];
1. Чтобы функция была чистой - я использую `slice()`, поскольку в таком случае возвращается новый массив, в который копирует элементы в указанном диапазоне. И уже к новому массиву применяется `reverse()`
2. Если отказаться от использования `reverse()`, то можно было бы использовать `reduce()` - итерируясь по массиву, добавлять текущий элемент в начало нового массива:
```js
arr.reduce((accumulator, value) => {
  return [value, ...accumulator]
}, [])
```

2021-02-08 11:31 UTC, Tullerpeton commented
Исправил:
1. JSDoc для функции `inverse()`
2. Код стайл
3. Написал, как можно заменить `reverse()`

2021-02-08 15:10 UTC, Betchika99 commented on source/inverse.js
> +		throw new TypeError('Incorrect input data');
код стайл - отступ какой-то странный

2021-02-08 15:10 UTC, Betchika99 commented on source/inverse.js
> +* @param {Array} array An array of elements
В твоем случае есть много корректных вариантов. Можно использовать `Array.<*>`, `*[]` и даже просто `Array` ( несмотря на то, что в JS нет такого типа, JSDoc это позволяет). Но обычно указывают `number[]` или `string[]`, когда используется конкретный тип для массива. Запомни, это пригодится :)

2021-02-08 15:10 UTC, Betchika99 requested changes
Последний рывок

2021-02-08 15:36 UTC, Tullerpeton commented
Исправления:
1. Код стайл - 0ae022c

2021-02-10 22:16 UTC, closed without merging