Муравьев Илья, АПО-22, Вариант 2
frontend-park-mail-ru/homework_2021_1 pull request #23
Opened 2021-02-09 12:22 UTC by PiroDev

Здравствуйте!

2021-02-09 17:12 UTC, tmible requested changes
Привет, добро пожаловать на лучший в Технопарке курс — курс фронтенда!

Здорово, что ты написал много полезных тестов! А ещё лайк за spread, разделение на функции, тернарный оператор и всякие `filter()` и `slice()`.

Но всё же пару мест, к которым можно придраться, я нашёл ;)
А так всё очень даже неплохо

2021-02-09 17:19 UTC, tmible commented on source/euclid.js
> +function euclid(...values) {
Давай лучше стрелочную функцию
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2021-02-09 17:57 UTC, PiroDev commented on source/euclid.js
> +    for (let secondNumber of numbers.slice(1)) {
Заменил цикл `for` на метод `reduce()`

2021-02-09 18:13 UTC, PiroDev reviewed
Исправления в 8a90a71:
- Сделал сравнения явными
- Сделал функцию `euclid()` стрелочной
- Заменил реализацию через цикл `for` на более подходящий метод `reduce()`

2021-02-09 19:01 UTC, tmible requested changes
`reduce`? Моё почтение! Честно говоря, ожидал просто `forEach()`. Здорово, здорово

2021-02-09 19:35 UTC, PiroDev commented on source/euclid.js
> +    if (naturalNumbers.length == 0) {
Различия я понимаю, но не совсем понял какая разница будет конкретно в этом случае. Может только если изменить само поле length, возникнут возможные ошибки, но этим же вряд ли кто-то будет заниматься. Или есть еще какие-то подводные камни?

2021-02-09 19:40 UTC, PiroDev commented on source/euclid.js
> +    return numbers.reduce(reducer);
Название `findGCD` мне кажется крайне подходящим, поэтому его оставил

2021-02-09 19:56 UTC, tmible commented on source/euclid.js
> +    if (naturalNumbers.length == 0) {
Конкретно в этом случае на ограниченном наборе проверенных данных разницы действительно не будет. Просто лучше привыкнуть использовать `===` как более надёжную штуку, потому что ох уж эта типизация в js! В общем, если ты хочешь сократить проверку на равенство и исключить из неё явный каст, используй `==`. В остальных случаях, наверное, несколько суеверно традиционно используется `===`. Надеюсь, я внёс немного ясности, а не наоборот. Дай знать об этом обязательно! Если что, будем разбираться, чтобы все всё поняли

2021-02-09 20:01 UTC, tmible commented on source/euclid.js
> +    return numbers.reduce(reducer);
@PiroDev оно действительно крайне подходящее. Ты меня правильно понял. На первом уровне вложенности запрещены функции с глупыми названиями типа `reducer` (за них отдельный котёл в аду)

2021-02-09 20:02 UTC, PiroDev commented on source/euclid.js
> +    if (naturalNumbers.length == 0) {
Всё, понял - просто мало ли тут правда какой-то случий упустил. Так всё понятно, буду привыкать к `===`.

2021-02-09 20:14 UTC, tmible requested changes
Осталась вишенка и торт будет готов

2021-02-09 20:14 UTC, tmible commented on source/euclid.js
> +const findGCD = (firstNumber, secondNumber) => {
Ну нет(
Нейминг надо добить. Reduce не то что бы пару элементов рассматривает. Думаю, суть самой свёртки может натолкнуть тебя на идею

2021-02-09 20:24 UTC, PiroDev commented on source/euclid.js
> +const findGCD = (firstNumber, secondNumber) => {
Я думал над этим, но ведь эту функцию можно и отдельно где-то ещё использовать. Если оставлять её только для `reduce`, то я бы её просто в `euclid` реализовал и не стал бы её вообще выносить. Ну можно в неё саму проверки тогда ещё добавить на валидность аргументов, чтобы она уже стала совсем "самостоятельной", но тоже кажется, что это неоднозначно, потому что в спецификации написано, что принимаются только натуральные числа.
А если функция используется независимо от `reduce`, то намного понятнее и, как по мне, логичнее с таким названием её и оставить.

2021-02-10 11:52 UTC, tmible commented on source/euclid.js
> +const findGCD = (firstNumber, secondNumber) => {
@PiroDev согласен. Тогда, давай всё-таки сделаем её совсем самостоятельной: с проверками входных данных и отдельными тестиками

2021-02-10 17:38 UTC, PiroDev commented on source/euclid.js
> +const findGCD = (firstNumber, secondNumber) => {
Еще раз подумал и решил не дублировать проверки - так даже тесты одни и те же получаются. Изменил название и занес её в `euclid()`, как ты изначально и предложил сделать.

2021-02-10 18:01 UTC, tmible commented on source/euclid.js
> +const findGCD = (firstNumber, secondNumber) => {
@PiroDev просто из интереса спрашиваю: почему не сделал анонимной? В смысле с объявлением прямо в вызове `reduce()`

2021-02-10 18:03 UTC, tmible commented
Вот теперь неплохо. Жди апрув

2021-02-10 18:19 UTC, PiroDev commented on source/euclid.js
> +const findGCD = (firstNumber, secondNumber) => {
Там цикл с тернарником и еще две строки помимо этого... слишком громоздко заключать это сразу в `reduce()`, как по мне. Сразу вспоминаю примеры нечитаемого кода в одну строчку)
Было бы там две строчки, ну может даже три коротких строчки - не думая засунул бы сразу в вызов reduce.

2021-02-10 22:17 UTC, closed without merging

2021-02-16 19:44 UTC, zelflod commented on source/euclid.js
> +    const reducerGCD = (accumulatedGCD, currentNumber) => {
Почему бы не вынести эту функцию отдельно?  Будет красиво

2021-02-16 20:00 UTC, tmible commented on source/euclid.js
> +    const reducerGCD = (accumulatedGCD, currentNumber) => {
Обсуждали выше. Чтобы не делать в ней проверки типов, не писать отдельные тесты. Было два варианта: самостоятельная полноценная функция и карманная на один раз, просто чтобы в вызове `reduce()` не писать многабукаф. Был выбран второй вариант