Work Done
frontend-park-mail-ru/homework_2021_1 pull request #25
Opened 2021-02-09 12:33 UTC by AzisHop

2021-02-09 18:42 UTC, tmible requested changes
Привет, добро пожаловать на лучший в Технопарке курс — курс фронтенда!

Кажется, ты забыл про тестики(
Они тут точно нужны

2021-02-09 18:42 UTC, tmible commented on source/inverse.js
> +    if (flag >= 0) {
Грустно видеть здесь `if`, а не тернарный оператор. Если придумаешь способ с ним, будет отлично! Если нет, то ничего страшного

2021-02-09 20:33 UTC, tmible commented on source/inverse.js
> +const inverse = (arr, flag) => {
И добавь, пожалуйста, JSDoc к функции. Это очень полезно!

2021-02-09 21:10 UTC, AzisHop commented
Привет! Спасибо) Все исправил.
1) Сделал другую проверку на тип данных.
2) Убрал if/else, поставил вместо них тернарный оператор.
3) Добавил тесты и JSDoc.

2021-02-09 21:16 UTC, AzisHop commented on source/inverse.js
> +        var tmp = arr.splice(flag);
Как я понял, ты говоришь про const) Но так как я поменял if/else на тернарный оператор, то его уже увы не поставишь :)

2021-02-10 11:41 UTC, tmible requested changes

2021-02-10 11:41 UTC, tmible commented on source/inverse.js
> +  * @returns {reverse_arr}
Что за тип возвращаемого значения такой?

2021-02-10 11:41 UTC, tmible commented on source/inverse.js
> +    return (flag >= 0) ? arr.splice(0, flag).concat(arr.reverse()) :
При всей моей любви к тернарникам, лучше уж `if`, чем такой тернарник. Важно, чтобы код был понятным и легко читался

2021-02-10 13:15 UTC, AzisHop commented on source/inverse.js
> +    return (flag >= 0) ? arr.splice(0, flag).concat(arr.reverse()) :
Ну я поэтому иф и делал

2021-02-10 13:32 UTC, AzisHop commented
Пофиксил.
1) Вернул старую логическую схему с if/else.
2) Поправил JSDoc.

2021-02-10 14:19 UTC, tmible requested changes

2021-02-10 14:50 UTC, AzisHop commented on source/inverse.js
> +        var tmp = arr.splice(flag);
Упс, сорян :)))

2021-02-10 14:51 UTC, AzisHop commented
Поправил))

2021-02-10 15:28 UTC, tmible commented on source/inverse.js
> +    if (typeof flag != "number") {
Ну блин, почему же `!=`?(

2021-02-10 15:37 UTC, AzisHop commented on source/inverse.js
> +    if (typeof flag != "number") {
старая сишная привычка) поправил

2021-02-10 15:41 UTC, tmible reviewed
Супер! Отправляю на апрув

2021-02-10 22:17 UTC, closed without merging