Никита Волков, Вариант 8
frontend-park-mail-ru/homework_2021_1 pull request #26
Opened 2021-02-09 15:24 UTC by VolkovNik

2021-02-10 14:04 UTC, Betchika99 requested changes
Приветствую тебя на курсе фронтенда! Впереди тебя ждут классный семестр, очень плодотворная работа и (я уверена) классный продукт в портфолио. Заранее желаю тебе удачи :)
Ты отлично справился с дз0, но есть некоторые замечания и вопросы к твоему решению. Я думаю, ты легко с ними справишься и быстро получишь свои заветные баллы. Если возникнут какие-то сложности, можешь смело писать мне в телеграм @emdobryanskaya

2021-02-10 14:04 UTC, Betchika99 commented on tests/sort.js
> +	});
смотри, а что будет если я передам некорректные данные, но в строке? Например '123' или объект JSON в строке? Можем это обработать и протестировать?

2021-02-10 14:55 UTC, VolkovNik commented on source/sort.js
> +	if (typeof(string) !== 'string') {
Оператор строгого равенства === проверяет равенство без приведения типов, а операнды == преобразуются в числу

2021-02-10 14:59 UTC, VolkovNik commented on source/sort.js
> +	const collator = new Intl.Collator();
Intl.Collator является конструктором сортировщиков, которые зависят от языка (необходимо, потому что обычный sort не учитывает букву ё в русском алфавите), соответственно объявляю сортировщик collator

2021-02-11 15:05 UTC, VolkovNik commented on source/sort.js
> +	if (typeof(string) !== 'string') {
Наврал, == приводит операнды к какому-то общему типу в зависимости от входных данных, а не всегда приводит к числам

2021-02-13 13:18 UTC, closed without merging