Усков Даниилб вариант 9, АПО-22
frontend-park-mail-ru/homework_2021_1 pull request #28
Opened 2021-02-09 17:32 UTC by CUzkov

2021-02-09 18:08 UTC, gavroman commented
Привет! Добро пожаловать на мой любимый курс технопарка!
Уважение за использование стрелочных функций, еще и без `{}`, и тернарников. 
Круто, когда можно написать функцию в 1 строчку, но согласись, это не всегда оправданно. Код в первую очередь должен быть читаемым и понятным всем - его читают намного чаще чем пишут.  Есть парочка предложений:
1) Давай все таки сделаем функцию более структурированной и читаемой, добавим больше переменных и констант, условных операторов, разнесем на смысловые блоки и тд. 
2) Что если в твою функцию попадет не то, что ты там ожидаешь получить? Например `[null]`. Давай добавим проверок на валидность входных данных и тестов не это дело
3) Чтобы код был понятнее всем кто его читает принято писать jsDoc коменты, предлагаю к твоим функциям тоже написать

2021-02-09 18:09 UTC, gavroman commented on source/anagram.js
> +'use strict'
Расскажи плиз, для чего это нужно, на что влияет?

2021-02-09 18:09 UTC, gavroman commented on source/anagram.js
> +'use strict'
+ потерялась `;`

2021-02-09 18:11 UTC, gavroman commented on source/anagram.js
> +    // В данном кейсе лаконичнее без {}
Лаконичнее - не всегда значит лучше. Обычно такие вещи регулируются линтером, и раз у тебя на 26 строчке ифак с `{}`, давай тут тоже сделаем по красоте

2021-02-09 18:12 UTC, gavroman commented on source/anagram.js
> +    Array.isArray(words) ? words.reduce(
Почему тут используешь именно `reduce`? Обычно его юзают для превращения массива в какой-то 1 объект, число и тд. Мб подберем что-то более подходящее отсюда https://learn.javascript.ru/array-methods ?

2021-02-09 18:13 UTC, gavroman commented on source/anagram.js
> +let anagram = (words) => (
почему `let`, а не `const`?

2021-02-09 18:13 UTC, gavroman commented on source/anagram.js
> +                acc.push(el.sort())
потерялась `;`

2021-02-09 18:14 UTC, gavroman commented on source/anagram.js
> +    // тест не очень, смылс сортировки по первому слову....
Не совсем понял, о чем этот комент

2021-02-09 18:14 UTC, gavroman commented on source/anagram.js
> +)
го добавим `;` и перенос строки в конец файла

2021-02-09 18:15 UTC, gavroman commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно', function (assert) {
зачем один и тот же тестик 2 раза?

2021-02-09 18:16 UTC, CUzkov commented on source/anagram.js
> +    Array.isArray(words) ? words.reduce(
тут очень удобно юзать его аккумулятор, чем объявлять выше и брать его из контекста

2021-02-09 18:26 UTC, CUzkov commented on source/anagram.js
> +    // В данном кейсе лаконичнее без {}
prettier не заменил на скобки, да и на работа так пишем, в данной ситуации лаконичность специфичной функи делает её более читаемой, чем ещё 6 строк сверху

2021-02-09 18:28 UTC, CUzkov commented on source/anagram.js
> +    // тест не очень, смылс сортировки по первому слову....
встроенный тест странный, подмассивы зачем-то нужно отсортировывать по первому слову, хотя их там может быть и 3 и не с одной буквы

2021-02-09 18:29 UTC, CUzkov commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно', function (assert) {
не один и тот же, тут кидаю null, там строку

2021-02-09 18:47 UTC, CUzkov commented on source/anagram.js
> +let anagram = (words) => (
done

2021-02-09 18:47 UTC, CUzkov commented on source/anagram.js
> +                acc.push(el.sort())
done

2021-02-09 18:47 UTC, CUzkov commented on source/anagram.js
> +)
done

2021-02-09 18:48 UTC, CUzkov commented
1) ОК
2) Так уже были тесты, в чём прикол? Проверяю isArray, что ещё проверять?
3) ОК

2021-02-09 18:49 UTC, CUzkov commented on source/anagram.js
> +'use strict'
легче ошибки искать, особенно если без ts и линтеров всяких кодить

2021-02-09 19:44 UTC, gavroman commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно', function (assert) {
тогда назови тескейсы по-разному, или вообще в 1 с названием 'Функция работает правильно c невалидными данными'

2021-02-09 19:49 UTC, gavroman commented
Все ок, кроме тестов проверки на невалидные входные данные и тестов на эти случаи

2021-02-09 19:56 UTC, gavroman requested changes
отписал

2021-02-09 20:01 UTC, CUzkov commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно', function (assert) {
сори, исправил

2021-02-09 20:28 UTC, gavroman requested changes
какая строчка выстрелит при вызове `anagram([100500])`?

2021-02-09 20:36 UTC, gavroman commented
Другими словами: почему массив из falsy значений обрабатывается, а массив других типов данных нет?

2021-02-10 13:17 UTC, CUzkov commented
> Другими словами: почему массив из falsy значений обрабатывается, а массив других типов данных нет?

исправил, теперь обрабатываю только строки в массиве, остальное фильтрую

2021-02-10 16:10 UTC, gavroman reviewed
теперь красота, апруве!

2021-02-10 22:17 UTC, closed without merging