Добавлено: Код решения, тесты
frontend-park-mail-ru/homework_2021_1 pull request #31
Opened 2021-02-09 21:58 UTC by IfuryI

Здравствуйте. Проверьте, пожалуйста, ДЗ0

2021-02-10 18:41 UTC, zelflod commented on source/roman.js
> +'use strict'; // Включает строгий режим
Надеюсь ты понимаешь что значит "строгий режим". А коммент тут избыточен

2021-02-10 18:46 UTC, zelflod commented on source/roman.js
> +    const thous = ["","M","MM","MMM","MMMM"];
Этот файлик -- можно считать модулем. Давай вынесем константы в самый верх модуля. Функция сохранит доступ к константам (слава замыканию!). Профит: при каждом вызове функции не будут создаваться новые константы

2021-02-10 18:47 UTC, zelflod commented on source/roman.js
> +    const thous = ["","M","MM","MMM","MMMM"];
лучше не сокращай имена переменных, ухудшается читаемость

2021-02-10 18:48 UTC, zelflod commented on source/roman.js
> +    const o = ones[parseInt(num % 10)];
лше не сок име перемнх, ухудшся читмсть

2021-02-10 18:49 UTC, zelflod commented on source/roman.js
> +    return res;
можно сразу `return t + h + te + o;`

2021-02-10 18:51 UTC, zelflod commented on source/roman.js
> +	str = str.toUpperCase();
Что если `str` -- не строка? Давай обрабатывать аргументы на валдиность

2021-02-10 18:54 UTC, zelflod commented on source/roman.js
> +const numCorrectnesCheck = (str, containsOf) => {
`checkNumCorrectnes`  лучше звучит. Функция -- это действие, поэтому стоит начать с глагола

2021-02-10 19:02 UTC, zelflod commented on source/roman.js
> +	else if (typeof numToConvert === "string" && numToConvert.length != 0) {
`else`  не нужен, если попадем в первый блок if, то return прекращает дальнейшее выполнение функи.

В js для читаемости делают так:
```
if () {
    return ...;
}

if () {
    return ...;
}

if () {
    return ...;
}

return ...;
```

2021-02-10 19:03 UTC, zelflod commented on source/roman.js
> +	return null;
В двух местах возвращаешь null. Давай только вначале. Если пройдем начальное условие, то нужно точно что-то возвращать.

2021-02-10 19:06 UTC, zelflod commented on source/roman.js
> +    if (ret < 0 || ret > 3999) {
3999 -- магическая константа. Что это? Зачем это? Почему это? Не отвечай на мои вопросы, сделай так чтобы их не было

2021-02-10 19:08 UTC, zelflod commented on source/roman.js
> + * @returns {res} result - integer number or string (converted number)
добавь тип аргумента и возвращаемого значение

2021-02-10 19:11 UTC, zelflod commented on tests/roman.js
> +		assert.strictEqual(roman(''), null);
что если на вход подать null, undefined, 0, [], {}?

2021-02-10 19:17 UTC, zelflod commented on source/roman.js
> +	if (typeof numToConvert === "number" && Number.isInteger(numToConvert) === true &&
Подумай, можно ли упростить эти условия или отказаться от них в пользу более простых условий

2021-02-10 19:19 UTC, zelflod commented on source/roman.js
> +	for (let i = 0; i < str.length; i++) {
попробуй прекрасные методы массов https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#

Постарайся использовать эти методы там где они упростят читаемость кода

2021-02-10 19:28 UTC, zelflod requested changes
Приветствую на курсе Фронтенда!

Лайк за JSDoc! 

Давай править замечания и пробовать упростить решение

2021-02-10 20:19 UTC, IfuryI commented on source/roman.js
> +	str = str.toUpperCase();
Обрабатываю в функции roman

2021-02-10 20:23 UTC, IfuryI commented on source/roman.js
> +	return null;
В первый раз null возвращается если аргумент вообще не валидный, в конце - если аргумент не имеет нужный формат для конвертации (не число или строка нужного формата). Не могу чето придумать, как красиво сделать с одним нулом

2021-02-10 20:28 UTC, IfuryI commented on source/roman.js
> +	for (let i = 0; i < str.length; i++) {
Думал использовать вместо обычного цикла arr.forEach, но у меня тут строка...

2021-02-10 20:39 UTC, IfuryI commented on source/roman.js
> +	str = str.toUpperCase();
Или лучше делать и там и там?

2021-02-11 09:16 UTC, zelflod commented on source/roman.js
> +	str = str.toUpperCase();
Лучше и там и там

2021-02-11 10:09 UTC, zelflod commented on source/roman.js
> + * @param {num} number - given integer number
Йоу, вроде я уже просил типы добавить для аргументов и возвращаемого значения, а ты поменял только там где я просил (функции roman), а не везде. Принимай плз замечания не точечно, а глобально, файлик то небольшой)

2021-02-11 10:36 UTC, zelflod commented on source/roman.js
> +    let ret = 0;
Обращай. плиз на читаемость и понятность названий переменных

2021-02-11 10:48 UTC, zelflod commented on source/roman.js
> +function arabicToRoman(num) {
что будет, если передать число > 3999? или  < 1? Каждая функция должна вести себя ожидаемо

2021-02-11 11:10 UTC, zelflod commented on source/roman.js
> +	return null;
Что значит "вообще не валидный"? 
Что значит "валидный"? 
Если бы была переменная isValid, то какого типа она была бы? 
Что значит "аргумент не имеет нужный формат для конвертации (не число или строка нужного формата)"?
Что ты проверяешь в строке `if (!numToConvert)`?
Что ты проверяешь в `numToConvert.length != 0`?

Нет ли у тебя ощущения, что понятия смещались, раздвоились, даже размножились? Я верю, у тебя получится с одним нулом

2021-02-11 11:10 UTC, zelflod commented on source/roman.js
> + * @returns {res} result - integer number or string (converted number)
тут добавил, в остальных местах - нет

2021-02-11 11:12 UTC, zelflod commented on source/roman.js
> +	for (let i = 0; i < str.length; i++) {
преврати строку в массив, `.split('')`

2021-02-11 11:19 UTC, zelflod commented on source/roman.js
> +        numToConvert >= minRomanNumber && numToConvert <= maxRomanNumber) {
Пусть валидность аргумента проверяет сама `arabicToRoman `, тут только проверь нужно использовать `arabicToRoman` или нет. Тогда `arabicToRoman ` станет более самостоятельной. 

Сейчас функа `roman` похожа на старый родитель, который контролирует своих детей везде и всегда, а `arabicToRoman` похож на мамкина 40 летнего сына, живущего в доме родителей, который   отпрашивается чтобы сходить на свидание

2021-02-11 11:30 UTC, zelflod commented on source/roman.js
> +    while (i >= 0 && pos < str.length) {
Преврати строку в массиву и используй метод массива для итерации

2021-02-11 11:31 UTC, zelflod commented on source/roman.js
> +const checkNumCorrectnes = (str, containsOf) => {
Не думал про встроенные методы проверки соответствия строки к какому-либо шаблону?

2021-02-11 11:33 UTC, zelflod requested changes
Обрати внимание на замечания и исправляй недочеты глобально, а не только в одном месте

2021-02-11 19:27 UTC, IfuryI commented on source/roman.js
> +    while (i >= 0 && pos < str.length) {
Тут точно это нужно? Просто алгоритм пропускает символы строки, а forEach по всем пройдется. Не знаю чето как и какие методы можно тут красиво применить

2021-02-11 19:27 UTC, IfuryI commented on source/roman.js
> +const checkNumCorrectnes = (str, containsOf) => {
Сделал через регулярку

2021-02-11 19:55 UTC, zelflod commented on source/roman.js
> +const checkNumCorrectnes = (str, containsOf) => {
С регуляркой отпадает необходимость в функции `checkNumCorrectnes`. 

Тогда можешь использовать литеральную запись регулярки

2021-02-11 19:57 UTC, zelflod commented on source/roman.js
> +        if (checkNumCorrectnes(numToConvert, "I,V,X,L,C,D,M") === true) {
можно проще `if (smth) {}` вместо `if (smth === true) {}`

2021-02-11 20:01 UTC, zelflod commented on source/roman.js
> +        else {
else тебе не нужен

2021-02-11 20:12 UTC, IfuryI commented on source/roman.js
> +        if (checkNumCorrectnes(numToConvert, "I,V,X,L,C,D,M") === true) {
точно

2021-02-11 20:24 UTC, IfuryI commented on source/roman.js
> +const checkNumCorrectnes = (str, containsOf) => {
Исправил

2021-02-12 07:18 UTC, zelflod requested changes

2021-02-12 07:18 UTC, zelflod commented on source/roman.js
> +            return null;
тут наверное нужно возвращать previousValue

2021-02-12 07:18 UTC, zelflod commented on source/roman.js
> +        if (!!numToConvert.match(/^[I,V,X,L,C,D,M]+$/i)) {
Зачем в регексе запятые? Точно они нужны?

2021-02-12 07:29 UTC, zelflod requested changes

2021-02-12 07:29 UTC, zelflod commented on source/roman.js
> +    if (str.length === 0 || str.length > maxRomanNumLength) {
Если str - undefined, например, то у тебя будет ошибка "cannot read property length of undefined". Тебе нужно проверить что str -- строка.

Проверить, что строка пустая можно проверить так !str

2021-02-12 07:29 UTC, zelflod commented on source/roman.js
> +    if (typeof numToConvert === "string" && numToConvert.length != 0) {
если numToConvert - пустая строка, то не пройдет регулярку, проверять тут не надо

2021-02-12 07:29 UTC, zelflod commented on source/roman.js
> +        if (!!numToConvert.match(/^[1,2,3,4,5,6,7,8,9,0]+$/i)) {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

таким образом не нужны будут `!!`

2021-02-12 16:40 UTC, IfuryI commented on source/roman.js
> +            return null;
Исправил

2021-02-12 16:41 UTC, IfuryI commented on source/roman.js
> +        if (!!numToConvert.match(/^[I,V,X,L,C,D,M]+$/i)) {
Не нужны, убрал

2021-02-12 16:41 UTC, IfuryI commented on source/roman.js
> +    if (str.length === 0 || str.length > maxRomanNumLength) {
Переделал

2021-02-12 16:41 UTC, IfuryI commented on source/roman.js
> +    if (typeof numToConvert === "string" && numToConvert.length != 0) {
убрал эту проверку

2021-02-12 16:41 UTC, IfuryI commented on source/roman.js
> +        if (!!numToConvert.match(/^[1,2,3,4,5,6,7,8,9,0]+$/i)) {
Исправил

2021-02-13 14:11 UTC, zelflod approved these changes

2021-02-13 14:51 UTC, Drujininii requested changes

2021-02-13 14:51 UTC, Drujininii commented on source/roman.js
> +}
мои соболезнования. трудная задачка попалась

2021-02-13 14:53 UTC, Drujininii commented on source/roman.js
> +}
Случайно запросил правки, не могу с мобилки зареволвит , пардон)))

2021-02-13 18:21 UTC, closed without merging