add function and tests
frontend-park-mail-ru/homework_2021_1 pull request #32
Opened 2021-02-09 22:45 UTC by wh75er

Андрей Киселев
АПО 21
Вариант 17

2021-02-10 09:26 UTC, Sarafa2n reviewed
Привет и добро пожаловать на курс фронтенда! Тебя ждет увлекательное погружение в мир фронтенда. И желаю тебе удачи!
Ты хорошо справился с заданием, но есть некоторые замечания по коду. Думаю ты легко сможешь с ними справишься, если будут вопросы можешь спрашивать)

2021-02-10 10:00 UTC, wh75er commented on source/plainify.js
> +      }
Все замечания понятны, кроме рекурсии. Переписать с использованием рекурсии только в качестве задания или есть какие-то преимущества над итеративной реализацией?

2021-02-10 10:07 UTC, Sarafa2n commented on source/plainify.js
> +      }
Ну смотри в больших проектах (проде) на клиенте, в большинстве своем, использование рекурсии означает, что есть какая-то ошибка в бизнес-логике. Это часто замедляет процесс рендеринга и очень часто приводит к ошибкам. 

В нашем же случае если сделать рекурсией можно сделать более читаемое решение.

2021-02-10 14:01 UTC, wh75er commented
Все поправил, теперь работает через reduce и рекурсию

2021-02-10 17:31 UTC, Sarafa2n commented on source/plainify.js
> +  return prev
Можно намного проще с использованием всего 1 `reduce`.
И можно рекурсивно вызывать `plainify`. Подумай как это можно сделать, если будут вопросы пиши

2021-02-10 17:31 UTC, Sarafa2n commented on source/plainify.js
> +const cutObjDepth = (prev, [key, value]) => {
Лучше передавать как один объект, и деструктурировать внутри функции.

2021-02-10 19:50 UTC, wh75er commented on source/plainify.js
> +  return prev
я правильно понял, что 1 reduce в коде вцелом, а не только в одной из функций?

2021-02-10 19:52 UTC, wh75er commented on source/plainify.js
> +  if (typeof value === 'object' && value !== null) {
Проверку на объект? Это ведь и так уже часть функции, не понял этот момент (

2021-02-10 19:57 UTC, Sarafa2n commented on source/plainify.js
> +  return prev
в этой функции, в целом можно двумя

2021-02-10 19:58 UTC, Sarafa2n commented on source/plainify.js
> +  if (typeof value === 'object' && value !== null) {
ну смотри, ты делаешь проверку на объект в этой функции, и в `plainify`, зачем одно и тоже копипастить, лучше вынести проверку в отдельную функцию

2021-02-10 20:51 UTC, wh75er commented on source/plainify.js
> +  }
Да я тут тупанул, подумал, что с null будет работать в этом случае

2021-02-10 20:51 UTC, wh75er commented on source/plainify.js
> +  if (typeof value === 'object' && value !== null) {
А, все, это справедливо

2021-02-10 20:52 UTC, wh75er commented on source/plainify.js
> +  return prev
Я просто переписал вроде, но у меня не получается от второй вложенности избавиться. У меня там forEach используется для стирания старых ключей и добавления новых

2021-02-10 21:09 UTC, wh75er commented
Так, вроде все поправил. Теперь:

- Рекурсия вызывается через главную функцию
- Использутеся один reduce(но от вложенной итерации не сообразил как избавиться. Использую forEach, потому что изменяется не массив, а объект)
- Деконструирую переменные в функции
- Вынес проверку на тип объекта в отдельную функцию

Еще вроде появилась идея как можно было бы сделать через один reduce, но пока не докрутил. Подумал, что можно переконвертить объект в массив сложный через entries и уже с массивом работать, а потом его назад конвертнуть с помощью fromEntries, но выяснилось, что entries не работает с deep объектами. Он только первый уровень конвертит в массив

2021-02-10 22:08 UTC, Sarafa2n commented on source/plainify.js
> +  return prev
Смотри, а давай переделаем эту функцию, чтобы она принимала только `curr`. И еще про 1 `reduce` имелось в виду про эту функцию конкретно. (кроме `reduce` нужно еще и проверка на объект, где можно тоже вернуть объект ключ: значение) Соответственно нужно будет еще внести коррективы и в функцию `plainify`, подумай, если совсем ничего не получится пиши, разберемся

2021-02-10 22:08 UTC, Sarafa2n commented on source/plainify.js
> +}
((
3 раз говорю, проверка данная не очень хорошая, так как она не полная, попробуй подставить туда `new Date()` к примеру.
Почитай вот тут про то, почему не так: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/typeof
Как можно сделать: https://stackoverflow.com/a/8511350/7844750

2021-02-11 07:37 UTC, wh75er commented on source/plainify.js
> +  let value = curr[1]
Там value меняется, поэтому value с let. Иначе придется заводить доп переменную

2021-02-11 07:42 UTC, wh75er commented on source/plainify.js
> +}
Сори, я недоглядел

2021-02-11 07:55 UTC, wh75er commented on source/plainify.js
> +  return prev
Я здесь вообще ничего не понимаю. Ты имеешь ввиду не инициализировать accumulator, а решить задачу с помощью reduce с дефолтным accumulator’ом, когда пишешь, чтобы reduce принимал только curr?

> кроме reduce нужно еще и проверка на объект, где можно тоже вернуть объект ключ: значение

Это тоже непонятно. Зачем функци проверки выдавать еще какой-то объект. Выглядит как усложнение кода, а еще не понятно где это может пригодиться

2021-02-11 08:08 UTC, Sarafa2n commented on source/plainify.js
> +  return prev
> Это тоже непонятно. Зачем функци проверки выдавать еще какой-то объект. Выглядит как усложнение кода, а еще не понятно где это может пригодиться
Смотри, в JS есть `spred` `rest` и ты можешь чтобы функция `cutObjDepth` возвращала объект, а в `plantify` через `spred` ключи объекта засовывать в acc в `reduce`. Вот про `spred`: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Spread_syntax

2021-02-11 08:10 UTC, Sarafa2n commented on source/plainify.js
> +  return prev
в `plantify` `reduce((acc, item) => ({ ...acc, ...cutObjDepth(item)}), {})`

2021-02-11 14:10 UTC, wh75er commented
Переписал plainify через спреды. Теперь та кринжовая конструкция ушла с тернарным оператором. Еще поменял проверку переменной на объект. Данная конструкция должна безошибочно выявлять, что пришел объект, который нужен

2021-02-11 14:19 UTC, Sarafa2n commented on source/plainify.js
> +    return value
Давай заменим на `reduce`, тут тоже можно сделать через `spred`, и тогда `value` будет `const` и функция получится чистой.
Кажется что 34 строка лишняя, можно же вызвать `plainify` внутри `entries`

2021-02-11 14:19 UTC, Sarafa2n commented on source/plainify.js
> +  return {[key]: value}
Логичнее сделать обратную проверку потому что у тебя внутри `if` будет лишь одна строка, и код станет более читаемым

2021-02-11 14:19 UTC, Sarafa2n commented on source/plainify.js
> +  return Object.prototype.toString.call(value) === '[object Object]'
Можно проще `Object.prototype === Object`

2021-02-11 19:44 UTC, wh75er commented on source/plainify.js
> +  return Object.prototype.toString.call(value) === '[object Object]'
Сейчас проверил. Нельзя так

```js
a = {a: 2, b: 3}

Object.prototype === a
false
```

2021-02-11 19:46 UTC, wh75er commented
Исправил forEach на reduce. Только вынес деконструирование curr объекта в аргументы функции reduce, чтобы return лишний не плодить, а то выглядело не очень

2021-02-11 20:03 UTC, Sarafa2n reviewed
Добавь тесты на невалидные данные

2021-02-11 21:37 UTC, Sarafa2n requested changes

2021-02-11 21:37 UTC, Sarafa2n commented on source/plainify.js
> +  return Object.entries(obj).reduce((acc, item) => ({...acc, ...cutObjDepth(item)}), {})
пробелы потерялись `{ ...acc, ...cutObjDepth(item) }`
Учись глазами работать как линтер)

2021-02-11 21:47 UTC, wh75er commented
- отформатил код
- добавил тесты на валидацию

2021-02-11 21:56 UTC, Sarafa2n requested changes
Ну вот, скажи, что решение стало намного проще чем было.
Давай, осталось чуть чуть

2021-02-11 21:56 UTC, Sarafa2n commented on source/plainify.js
> +    return {[key]: value}
тут тоже пробелы

2021-02-11 21:56 UTC, Sarafa2n commented on source/plainify.js
> +    }),
Можно в одну строку `({ ...acc, ['${key}.${in_key}']: in_value })`

2021-02-11 21:56 UTC, Sarafa2n commented on source/plainify.js
> +  )
Тоже можно в одну строку

2021-02-11 22:14 UTC, wh75er commented
Заформатил все и добавил в одну строчку

2021-02-11 22:16 UTC, Sarafa2n commented on source/plainify.js
> +};
Я понял
![image](https://user-images.githubusercontent.com/32399246/107705469-d30ff300-6ccf-11eb-9025-0ec13f88fda4.png)

2021-02-11 22:23 UTC, wh75er commented on source/plainify.js
> +};
![image](https://user-images.githubusercontent.com/26790838/107706148-eb344200-6cd0-11eb-9ea9-318693023b4c.png)

2021-02-11 22:26 UTC, wh75er commented on source/plainify.js
> +};
А, понял...

2021-02-11 22:27 UTC, wh75er commented
В общем просто через форматтер пропустил все, надеюсь ОК

2021-02-11 22:33 UTC, wh75er commented
Спасибо за терпение и сори за затупы. Непривычно писать такими конструкциями. Код реально стал намного меньше и понятнее. Буду стараться сразу писать то, что получилось после прохождения всего этого цикла

2021-02-13 14:50 UTC, Drujininii requested changes

2021-02-13 14:50 UTC, Drujininii commented on source/plainify.js
> +  return value != null && value.constructor === Object;
constructor является изменяемым свойством. проверка ненадежная. 
let a ={}
a.constructor = "any"

2021-02-13 18:06 UTC, wh75er commented
Вернул как было

2021-02-15 07:36 UTC, closed without merging