Лукаш Сергей АПО22
frontend-park-mail-ru/homework_2021_1 pull request #34
Opened 2021-02-09 23:02 UTC by Snikimonkd

2021-02-10 13:25 UTC, tmible requested changes
Привет, добро пожаловать на лучший в Технопарке курс — курс фронтенда!

Мощные тесты! Лайк за стрелочные функции.

Напиши, пожалуйста, JSDoc к своей функции — это очень полезно!

Довольно странная архитектура. Почему ты выбрал её, а не рекурсию?

2021-02-10 13:25 UTC, tmible commented on source/plainify.js
> +            if (typeof obj[key] === 'object') {
Этой проверки не хватит. Довольно сложный момент в js — в него нужно немного углубиться

2021-02-10 13:25 UTC, tmible commented on source/plainify.js
> +                    if (typeof obj[key][nextKey] == 'object') {
Что-то `=` потерялось? Ты знаешь про различия `==` и `===`?

2021-02-10 13:25 UTC, tmible commented on source/plainify.js
> +        obj = newObj;
Сможешь объяснить, почему делаешь именно так?

2021-02-10 14:40 UTC, Snikimonkd commented on source/plainify.js
> +    var flag = true;
Привет, мы тут общаемся? мб в телеге удобнее?

2021-02-10 15:21 UTC, tmible commented on source/plainify.js
> +    var flag = true;
@Snikimonkd по коду общаемся, конечно, тут

2021-02-10 15:40 UTC, Snikimonkd commented on source/plainify.js
> +    var flag = true;
Ну флаг нужен, чтобы цикл работал пока в объекте который я возвращаю есть "вложенные" объекты.
Рекурсию не выбрал, потому что всегда и везде говорили, что рекурсии лучше избегать, тут итак не очень читаемый код как мне кажется из-за того что работаю с вложенными объектами, так еще если рекурсию поставить то вообще ничего понятно не будет,

2021-02-10 15:40 UTC, Snikimonkd commented on source/plainify.js
> +    var ret = {};
Это не нужно, забыл убрать :-)

2021-02-10 15:40 UTC, Snikimonkd commented on source/plainify.js
> +    var ret = {};
Я в пн впервые увидел синтаксис JS, проходил курс на sololearn, так что не знал, что вар устарел

2021-02-10 15:40 UTC, Snikimonkd commented on source/plainify.js
> +        var newObj = Object();
а какой более js-ный?

2021-02-10 15:40 UTC, Snikimonkd commented on source/plainify.js
> +            if (typeof obj[key] === 'object') {
ну тут у меня тоже нет других идей

2021-02-10 15:40 UTC, Snikimonkd commented on source/plainify.js
> +                    if (typeof obj[key][nextKey] == 'object') {
ну как я понял "==" сравнивает по значению(5==5.0)-true, а "===" сравнивает с учетом типа(5===5.0)-false

2021-02-10 15:40 UTC, Snikimonkd commented on source/plainify.js
> +        obj = newObj;
здесь я убираю по очереди вложенности: obj=deep: {foo: 'bar', baz: 42}, newObj={deep.foo: 'bar',deep.baz: 42}, потом цикл проходит еще раз если есть вложенность и убирает следующую вложенность

2021-02-10 15:45 UTC, tmible commented on source/plainify.js
> +    var flag = true;
Хорошо, что ты понимаешь, зачем нужна эта переменная. Но мне, как человеку, впервые читающему твой код, совсем непонятно, что такое `flag`

2021-02-10 15:46 UTC, tmible commented on source/plainify.js
> +    var ret = {};
Обрати внимание на learn.javascript.ru
Это всегда актуальный учебник

2021-02-10 15:50 UTC, tmible commented on source/plainify.js
> +                    if (typeof obj[key][nextKey] == 'object') {
Да, коротко говоря, так. Посмотри тут
https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness

Лучше везде использовать `===`

2021-02-10 15:51 UTC, tmible commented on source/plainify.js
> +        obj = newObj;
Это понятно. Я имею в виду, зачем ты переприсваиваешь новый объект старому?

2021-02-10 16:00 UTC, tmible commented on source/plainify.js
> +    var flag = true;
К вопросу о рекурсии: как раз она здесь может значительно упростить твой код и избавить от необходимости делать лишнюю работу (итерироваться по всем ключам объекта каждый раз).
Рекурсии стоит избегать, если она очень много ресурсов отжирает. Здесь лучше сделать её, потому что она здорово упростит код и его логическую структуру, выигрывает по асимптотике (сокращает количество бесполезного выполнения кода). Не стоит панически избегать рекурсии, потому что может получиться так (как у тебя и получилось), что вариант без рекурсии работает сложнее и дольше.

2021-02-10 16:02 UTC, tmible commented on source/plainify.js
> +        var newObj = Object();
Ну уж объявление объекта в js ты можешь и сам загуглить

2021-02-10 16:02 UTC, Snikimonkd commented on source/plainify.js
> +        obj = newObj;
ну чтобы каждый раз цикл запускался по новому объекту, у которого убрана вложенность на один, если я не буду приравнивать новый объект старому то я буду ходить на одном и том же уровне и вложенность не будет убираться

2021-02-10 16:04 UTC, Snikimonkd commented on source/plainify.js
> +    var flag = true;
ну надо тогда переименовать на что-то вроде "isNested "

2021-02-10 16:10 UTC, tmible commented on source/plainify.js
> +            if (typeof obj[key] === 'object') {
Само собой. Очень хороший источник идей — гугл. Или всякие сайты с вопросами типа stackoverflow. Возможно, такой вопрос даже уже задавали)

2021-02-10 16:11 UTC, tmible commented on source/plainify.js
> +    var flag = true;
Ну, нейминг мы поправим, если что. Сейчас не это главное

2021-02-10 16:15 UTC, tmible commented on source/plainify.js
> +        obj = newObj;
Ну, такое переприсваивание — довольно нехорошо, потому что объекты в функции в js передаются всегда по ссылке, то есть ты в процессе работы функции портишь исходный объект

2021-02-11 05:07 UTC, tmible requested changes
Есть прогресс — это хорошо. Но решение можно сделать ещё меньше и оптимальнее

2021-02-11 05:07 UTC, tmible commented on source/plainify.js
> +    for (let key in obj) {
Зачем здесь `let`? Ты меняешь `key` в теле цикла? Поскольку в js динамическая типизация, стоит предпочитать `const`, потому что память под `const` выделяется один раз и навсегда, а за `let` надо ещё следить постоянно

2021-02-11 05:07 UTC, tmible commented on source/plainify.js
> +            for (let nextKey in obj[key]) {
То же самое про `let` и `const`

2021-02-11 05:07 UTC, tmible commented on source/plainify.js
> +        newObj = plainify(newObj);
Такой рекурсии, конечно же, стоит предпочесть `while`. Поищи другие варианты

2021-02-11 06:17 UTC, Snikimonkd commented on source/plainify.js
> +        newObj = plainify(newObj);
Сейчас у меня что-то вроде обхода в ширину, я могу предложить передавать в функцию строящийся ключ, тогда можно будет сделать обход в глубину, других идей пока нет

2021-02-11 09:13 UTC, Snikimonkd commented
вот придумал, как упростить, теперь без флага и рекурсия внутри цикла вызывается

2021-02-11 10:18 UTC, tmible requested changes

2021-02-11 10:18 UTC, tmible commented on source/plainify.js
> +            let nextObj = plainify(obj[key]);
Так, `nextObj` где-то меняется?

2021-02-11 10:18 UTC, tmible commented on source/plainify.js
> +        if (typeof obj[key] === 'object' && obj[key] != null) {
Кстати, `!=` тоже бывает двойным `!=` и тройным `!==`

2021-02-11 10:18 UTC, tmible commented on source/plainify.js
> +            for (var nextKey in nextObj) {
То же про `var`

2021-02-11 10:18 UTC, tmible commented on source/plainify.js
> +            for (var nextKey in nextObj) {
От этого цикла тоже можно (и даже нужно) избавиться. Всю работу этого цикла можно сделать в строке с вызовом рекурсии

2021-02-11 10:24 UTC, Snikimonkd commented on source/plainify.js
> +    for (var key in obj) {
Да что-то я торможу

2021-02-11 10:26 UTC, Snikimonkd commented on source/plainify.js
> +            for (var nextKey in nextObj) {
Тут как-то с foreach надо сделать?

2021-02-11 10:31 UTC, tmible commented on source/plainify.js
> +            for (var nextKey in nextObj) {
Нет, тут можно конструировать имя поля во внешнем `for`. Тогда при вызове рекурсии работа этого `for` будет выполнена во внешнем `for` внутри вызванного экземпляра функции

2021-02-11 14:01 UTC, Snikimonkd commented on source/plainify.js
> +            for (var nextKey in nextObj) {
У меня функция возвращает объект и я что-то не очень понимаю как не проходя по нему(без цикла) можно все его ключи сконкатинировать с прошлым ключем

2021-02-11 14:52 UTC, tmible commented on source/plainify.js
> +            for (var nextKey in nextObj) {
Можно, например, передавать первую часть ключа в рекурсию и в единственном `for` конкатенировать переданное значение и ключ, по которому итерируешься

2021-02-11 16:08 UTC, Snikimonkd commented on source/plainify.js
> +            for (var nextKey in nextObj) {
ну я так и сделал вроде

2021-02-11 16:23 UTC, tmible commented
Вот теперь хорошо. Убирай логи, актуализируй JSDoc и будем закругляться

2021-02-11 16:25 UTC, tmible commented on source/plainify.js
> + * const nected = {
Кстати, тут ошибочка

2021-02-11 16:41 UTC, Snikimonkd commented on source/plainify.js
> + * const nected = {
> Вот теперь хорошо. Убирай логи, актуализируй JSDoc и будем закругляться

А что в доке актуализировать, вроде все совпадает

2021-02-11 17:34 UTC, tmible commented on source/plainify.js
> + * const nected = {
А список параметров?

2021-02-11 18:16 UTC, Snikimonkd commented on source/plainify.js
> + * const nected = {
https://memepedia.ru/wp-content/uploads/2018/09/orehus-stiker.png

2021-02-13 14:47 UTC, Drujininii requested changes

2021-02-13 14:47 UTC, Drujininii commented on source/plainify.js
> +const plainify = (obj, lastKey) => {
надо проверить входные данные. тебе могут подсунуть в функу и undefined, и строку

2021-02-13 16:16 UTC, tmible commented on source/plainify.js
> +    if (typeof obj !== 'object' || obj == null) {
`=` потерялось

2021-02-13 16:16 UTC, tmible commented on source/plainify.js
> +    }
И второй параметр, конечно, тоже надо проверять)

2021-02-13 16:22 UTC, Snikimonkd commented on source/plainify.js
> +    }
а его мне по идее на нулл не надо проверять, потому что когда первый раз вызываю функцию там как раз нулл

2021-02-13 16:24 UTC, tmible commented on source/plainify.js
> +    }
Смотри в JSDoc. Там указано, что строка должна быть. Вот на неё и проверяй

2021-02-13 16:57 UTC, tmible requested changes

2021-02-13 16:57 UTC, tmible commented on source/plainify.js
> +    console.log(lastKey);
Логи убираем

2021-02-13 16:57 UTC, tmible commented on source/plainify.js
> +    if (typeof obj !== 'object' || obj === null || (lastKey !== 'string' && lastKey === null)) {
Длинноватое условие. Стоит разбить на 2 отдельные проверки

2021-02-13 16:57 UTC, tmible commented on source/plainify.js
> +    if (typeof obj !== 'object' || obj === null || (lastKey !== 'string' && lastKey === null)) {
Что-то с проверками `lastKey` явно не то

2021-02-13 17:27 UTC, tmible requested changes

2021-02-13 17:27 UTC, tmible commented on source/plainify.js
> +        console.log(lastKey);
Логи убирай

2021-02-13 17:27 UTC, tmible commented on source/plainify.js
> +    if (typeof lastKey !== 'string' && typeof lastKey !== 'object' && lastKey !== null) {
Зачем `typeof` для `lastKey`? Достаточно проверить, что это либо строка, либо `null`

2021-02-13 17:59 UTC, Snikimonkd commented on source/plainify.js
> +    if (typeof lastKey !== 'string' && typeof lastKey !== 'object' && lastKey !== null) {
а как проверить что это строка без тайпоф?

2021-02-13 18:05 UTC, tmible commented on source/plainify.js
> +    if (typeof lastKey !== 'string' && typeof lastKey !== 'object' && lastKey !== null) {
`typeof` со строкой нужен, конечно. Я имею в виду `typeof lastKey !== 'object'`

2021-02-15 07:35 UTC, closed without merging