Тяпкин Сергей, Вариант 8.
frontend-park-mail-ru/homework_2021_1 pull request #35
Opened 2021-02-09 23:17 UTC by SergTyapkin

2021-02-10 15:17 UTC, tmible requested changes
Привет, добро пожаловать на лучший в Технопарке курс — курс фронтенда!

Напиши, пожалуйста, JSDoc к своим функциям — это очень полезно!

2021-02-10 15:17 UTC, tmible commented on source/sort.js
> +а потому если нам надо сравнить с 'Ё', вместо этого сравниваем с 'Ж', разбирая случай, когда обе буквы равны.
Как раз для этих целей в js есть инструмент. Поищи его

2021-02-13 19:31 UTC, SergTyapkin commented on source/sort.js
> +    if (!string.length) return null;
На сайте, который нам скинули (в приветственном посте) было написано, что короткое однострочное тело if лучше оставлять на той же строке. Мне тоже показалось это странным

2021-02-13 19:32 UTC, SergTyapkin commented on source/sort.js
> +    let word, sentence = [];
Да нет. Word в самом коде ведь строкой потом является. Просто переменные были по смыслу связаны, потому решил их на одной строке оставить.

2021-02-13 19:34 UTC, SergTyapkin commented on source/sort.js
> +        if (string[i] == ' ') { // идём до первого пробела
Да, === вернет true только если и типы переменных совпадают.
Думаю, "a === b" это что-то вроде "a == b && typeof(a) == typeof(b)"

2021-02-13 20:05 UTC, SergTyapkin commented on source/sort.js
> +                }
Писать forEach для таких случаев - это действительно так принципиально?....

2021-02-13 20:50 UTC, SergTyapkin commented on source/sort.js
> +а потому если нам надо сравнить с 'Ё', вместо этого сравниваем с 'Ж', разбирая случай, когда обе буквы равны.
Никак не могу найти, к сожалению. Поиск ничего не даёт именно по этой теме. Вообще больше идей на этот счет нет

2021-02-13 20:59 UTC, tmible commented on source/sort.js
> +    if (!string.length) return null;
Короткое тело допустимо оставлять, но блок всегда в приоритете. Он всегда лучше читается

2021-02-13 21:00 UTC, tmible commented on source/sort.js
> +        if (string[i] == ' ') { // идём до первого пробела
Да, коротко говоря, так. Подробнее можешь посмотреть [тут](https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness)

2021-02-13 21:08 UTC, tmible commented on source/sort.js
> +                }
Нет, здесь итерация не по всем элементам, поэтому в таком случае `forEach()` не подойдёт совсем. И вообще его использование не принципиально, просто зачастую с ним получается короче и изящнее. Здесь я имею в виду, что мы не в С — не нужно вручную перебирать каждый символ ([вообще в js нет Сшных символов](https://learn.javascript.ru/string)), у строки много полезных методов

2021-02-13 21:25 UTC, tmible commented on source/sort.js
> +а потому если нам надо сравнить с 'Ё', вместо этого сравниваем с 'Ж', разбирая случай, когда обе буквы равны.
Посмотри [тут](https://learn.javascript.ru/intl))

2021-02-13 21:49 UTC, tmible requested changes

2021-02-13 21:49 UTC, tmible commented on source/sort.js
> +let comparator = (a, b) => {
Так, `comparator` где-то меняет значение? Вот [тут](https://medium.com/nuances-of-programming/%D0%B2-%D1%87%D1%91%D0%BC-%D1%80%D0%B0%D0%B7%D0%BD%D0%B8%D1%86%D0%B0-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-var-let-%D0%B8-const-%D0%B2-javascript-3084bfe9f7a3) посмотри про культуру использования `let` и `const`

2021-02-13 21:49 UTC, tmible commented on source/sort.js
> +const sort = function (string) {
Ну так эту уж тоже стрелочной тогда. Кстати, [тут](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions) про их различия можешь узнать

2021-02-13 21:49 UTC, tmible commented on source/sort.js
> +            if (word.length != 0) {
`=` потерялось

2021-02-13 21:53 UTC, tmible commented
Итак, чего ещё не хватает:
- [ ] JSDoc (очень!)
- [ ] использование встроенного компаратора, знающего букву ё

Если ты немного углубишься в методы строк и массивов и абстрагируешься от обычных сишных переборов строк по одному символу, может получиться очень короткое решение!

2021-02-14 18:24 UTC, SergTyapkin commented on source/sort.js
> +                }
Ну насчет forEach - нам не надо выполнять эту функцию только для первого символа, так что одной условной итерацией можно и пожертвовать, я так подумал.

2021-02-14 18:29 UTC, tmible commented on source/sort.js
> +                }
Не понял тебя. В любом случае повторюсь: `forEach()` тут не нужен точно. Я имел в виду другие методы строки

2021-02-14 19:04 UTC, SergTyapkin commented on source/sort.js
> +            if (word.length != 0) {
А зачем их вообще сравнивать через ===, если и string.length - это число, и 0 - тем более, и мы это точно знаем?

2021-02-14 20:10 UTC, tmible requested changes
Уже лучше!

Пожалуйста, проверяй каждый мой комментарий не только в той строке, к которой он написан, но и во всех остальных

2021-02-14 20:10 UTC, tmible commented on source/sort.js
> + * @param {number} a - Первая строка.
Как это `number`?

2021-02-14 20:10 UTC, tmible commented on source/sort.js
> +    let collator = new Intl.Collator('ru', {
Почему `let`? Он где-то меняется? Вообще подумай: нужно ли тебе тут создание этой переменной?

2021-02-14 20:10 UTC, tmible commented on source/sort.js
> +const sort = function (string) {
Функция всё ещё не стрелочная... :с

2021-02-14 20:10 UTC, tmible commented on source/sort.js
> +    let sentence = [];
Опять же, почему `let`?

2021-02-14 20:10 UTC, tmible commented on source/sort.js
> +    string.split(' ').forEach(item => {
`item` — не самое говорящее название. Точнее, самое не говорящее

2021-02-14 20:10 UTC, tmible commented on source/sort.js
> +    string.split(' ').forEach(item => {
Обрати внимание на метод `map()`

2021-02-14 20:10 UTC, tmible commented on source/sort.js
> +        item = item[0].toUpperCase() + item.join('').slice(1).toLowerCase(); // Слепляем первую большую и остаток - маленькие
Познай чейнинг (chaining) функций — отличная фича js

2021-02-14 20:10 UTC, tmible commented on source/sort.js
> +    let collator = new Intl.Collator('ru', {
Может, раз объявление стало таким коротким и перестало по сути быть функцией, занести его внутрь `sort()`?

2021-02-14 20:12 UTC, SergTyapkin commented on source/sort.js
> + * @param {number} a - Первая строка.
Странно - случайно опечатался

2021-02-14 20:13 UTC, SergTyapkin commented on source/sort.js
> +    let sentence = [];
Но я ведь меняю sentence...

2021-02-14 20:14 UTC, SergTyapkin commented on source/sort.js
> +    string.split(' ').forEach(item => {
А там просто в синтаксисе item было написано. Ну там можно три параметра ведь использовать - ну я и подумал, что будет понятнее, если я не буду как бы дефолтные имена трогать. Понял.

2021-02-14 20:21 UTC, tmible commented on source/sort.js
> +    let sentence = [];
Кажется, я об этом упоминал. Если нет, исправляюсь: объекты в js (а массив — это не что иное, как объект) существуют по ссылкам, поэтому изменением в контексте выбора `let`/`const` является присваивание переменной другой ссылке. Вот [тут](https://learn.javascript.ru/object) про это написано, например.

2021-02-14 20:27 UTC, SergTyapkin commented on source/sort.js
> +        item = item[0].toUpperCase() + item.join('').slice(1).toLowerCase(); // Слепляем первую большую и остаток - маленькие
так там одни функции меняют само значение переменной, а другие - нет. Так зачем строчку с присваиванием в скобки оборачивать, чтоб потом к ней через точку вторую приписывать... Это ж нечитаемо будет...

2021-02-14 20:34 UTC, tmible commented on source/sort.js
> +        item = item[0].toUpperCase() + item.join('').slice(1).toLowerCase(); // Слепляем первую большую и остаток - маленькие
Ну, здесь ужать в одну строку я не вижу способа, да. Но вот зачейнить `split()` и `sort()` -- почему бы и нет? Если переживаешь за читаемость, можно выносить каждый вызов на отдельную строку, но, на самом деле, тут это не требуется.
```
object
    .method1()
    .method2()
    .method3();
```

2021-02-14 20:40 UTC, SergTyapkin commented
Поправил. Всё равно не понимаю разницы между стрелочными функциями и обычными. Как я понял - они заменяют лямбда-функции из Си, а ещё там какие-то приколы с тем, что они не изменяют this. Так вот на в этом случае ни то ни другое не подходит и не понятно, зачем они в нашем случае...

2021-02-14 21:42 UTC, SergTyapkin commented on source/sort.js
> +        item = item[0].toUpperCase() + item.join('').slice(1).toLowerCase(); // Слепляем первую большую и остаток - маленькие
Ох ты, красиво, так можно было, оказывается. Спасибо, буду знать)

2021-02-15 07:34 UTC, closed without merging