Variant 19
frontend-park-mail-ru/homework_2021_1 pull request #36
Opened 2021-02-10 08:55 UTC by moroz-matros

Морозова Анастасия, АПО-21

2021-02-10 09:38 UTC, n-merkulova requested changes
приветствую тебя на курсе по фронтенду! :)

молодец, классная домашка - видно, что ты разбиралась с объектами и посмотрела стандарт ES6. давай поправим некоторые замечания, чтобы можно было поставить тебе максимальный балл

2021-02-10 09:38 UTC, n-merkulova commented on source/sorting.js
> +function sorting(initial, fields){
давай здесь тоже используем стрелочную функцию? знаешь, кстати, чем они отличаются от обычных?

2021-02-10 09:38 UTC, n-merkulova commented on source/sorting.js
> +    let copy = Object.assign([], initial);
лучше использовать здесь `const` вместо `let` -  обрати внимание на особенности работы с константными объектами

2021-02-10 09:38 UTC, n-merkulova commented on source/sorting.js
> +function sorting(initial, fields){
кстати, давай научимся документировать код и добавим для этой функции JSDoc?

2021-02-10 09:38 UTC, n-merkulova commented on source/sorting.js
> +            copy.sort((prev, next) => {
подумай, является ли твоя сортировка устойчивой? ты ведь не проверяешь никак равные значения. кстати, на такой кейс еще нужно будет добавить тестов)

2021-02-10 09:38 UTC, n-merkulova commented on source/sorting.js
> +    fields.reverse().forEach((item) => {
здесь, кстати, скобки у item необязательны

2021-02-10 09:38 UTC, n-merkulova commented on source/sorting.js
> +                if (prev[item] > next[item]) return 1;
обрати внимание на принятый в js кодстайл - лучше для блоков с условиями все же прописывать фигурные скобки

2021-02-10 09:38 UTC, n-merkulova commented on tests/sorting.js
> +	QUnit.test('sorting корректно работает с null в свойствах', function (assert) {
давай еще добавим как тесты, так и в самой функции обработку невалидных входных данных - что, если передан не массив? будет очень здорово, если сделаешь обработку ошибок с помощью исключений)

2021-02-10 20:01 UTC, moroz-matros commented on source/sorting.js
> +function sorting(initial, fields){
Исправлено. Стрелочные функции компактнее и у них нет своего this, то есть они обращаются в таком случае во внешнюю функцию? Из самых видимых отличий. Комменты исправлены

2021-02-10 20:01 UTC, moroz-matros commented on source/sorting.js
> +    let copy = Object.assign([], initial);
Принято, исправлено

2021-02-10 20:01 UTC, moroz-matros commented on source/sorting.js
> +            copy.sort((prev, next) => {
Добавлен возврат на равенство. На устойчивую сортировку уже вроде был прописан тест изначально

2021-02-10 20:02 UTC, moroz-matros commented on source/sorting.js
> +                if (prev[item] > next[item]) return 1;
Исправлено

2021-02-10 20:02 UTC, moroz-matros commented on source/sorting.js
> +    fields.reverse().forEach((item) => {
Исправлено

2021-02-10 20:03 UTC, moroz-matros commented on tests/sorting.js
> +	QUnit.test('sorting корректно работает с null в свойствах', function (assert) {
Попытка в try catch с тестом сделана :D

2021-02-13 14:44 UTC, Drujininii requested changes

2021-02-13 14:44 UTC, Drujininii commented on source/sorting.js
> +  const copy = Object.assign([], initial);
[...initial]

2021-02-13 14:44 UTC, Drujininii commented on tests/sorting.js
> +  });
нет тестов на сортировку строк. кириллицы/латиницы. в частности с использованием буквы "ё". так же тест на сортировку чисел в виде строк. входные данные: "12", "102", "1", "13","101"

2021-02-13 22:10 UTC, n-merkulova approved these changes

2021-02-14 10:32 UTC, moroz-matros commented on source/sorting.js
> +  const copy = Object.assign([], initial);
фикс

2021-02-14 10:32 UTC, moroz-matros commented on tests/sorting.js
> +  });
добавлено

2021-02-15 07:20 UTC, closed without merging