Чеклин Павел Вариант 3
frontend-park-mail-ru/homework_2021_1 pull request #37
Opened 2021-02-10 09:19 UTC by paulnopaul

2021-02-10 16:43 UTC, Betchika99 requested changes
Приветствую тебя на курсе фронтенда! Впереди тебя ждут классный семестр, очень плодотворная работа и (я уверена) классный продукт в портфолио. Заранее желаю тебе удачи :) 
Есть некоторые замечания к твоему решению. Я думаю, ты легко с ними справишься и быстро получишь свои заветные баллы. Если возникнут какие-то сложности, можешь смело писать мне в телеграм @emdobryanskaya

1) Ты не написал ни одного теста. Такое задание не может быть принято :(
2) Основную задачу твоя функция решает хорошо, но что будет, если в нее передадут кривые параметры? `isNaN` от любой строки вернет true и ты будешь пытаться выполнить перевод. Давай добавим в функцию валидацию, а также напишем негативные тесты, которые будут проверять это
3) Для удобного использования JS-функций разработчики пишут к своим функциям небольшую документацию прямо в коде. Добавь JSDoc (подробнее можешь почитать про нее [здесь](https://jsdoc.app/about-getting-started.html))
4) Давай придерживаться [стайл гайда JS](https://learn.javascript.ru/coding-style) и поправим отступы в твоем коде

некоторые замечания писала для одной строки, но такие же ошибки есть и в других местах кода. Пройдись по своему коду с проверкой :)

2021-02-10 16:43 UTC, Betchika99 commented on source/roman.js
> +const R_TO_D = {
давай будем называть переменные более однозначно. Название переменной должно однозначно говорить разработчику о ее назначении. Поэтому неоднозначные (например, `a`) и сокращенные названия не приветствуются

2021-02-10 16:43 UTC, Betchika99 commented on source/roman.js
> +const decimalToRoman = function (num) {
при объявлении всех функций лучше использовать [стрелочные функции](https://learn.javascript.ru/arrow-functions-basics). Чем они отличаются, можешь прочитать [здесь](https://learn.javascript.ru/arrow-functions)

2021-02-10 16:43 UTC, Betchika99 commented on source/roman.js
> +	}
Ознакомься с уже [существующими функциями языка](https://learn.javascript.ru/array-methods) JavaScript для работы с массивами. Обрати внимание на `reduce` и `forEach`

2021-02-10 16:43 UTC, Betchika99 commented on source/roman.js
> +	num = parseInt(num);
смотри, в данной строке ты изменяешь исходные данные. Это не очень хорошо. Все функции в идеале должны быть [чистыми](https://habr.com/ru/post/437512/).

2021-02-10 16:43 UTC, Betchika99 commented on source/roman.js
> +		let current = R_TO_D[num[i]];
неизменяемые переменные лучше всего обозначать через `const`, чтобы семантически было корректно. Почитать про отличия ключевых слов можно [здесь](https://learn.javascript.ru/variables)

2021-02-10 16:43 UTC, Betchika99 commented on source/roman.js
> +	let prev = 1001;
почему именно 1001? Какая-то рандомная константа необоснованная :(

2021-02-10 16:43 UTC, Betchika99 commented on source/roman.js
> +	}
так как у тебя есть обе ветви if и по итогу ты возвращаешь значение, то удобнее использовать [тернарный оператор](https://learn.javascript.ru/ifelse#uslovnyy-operator)

2021-02-10 16:43 UTC, Betchika99 commented on source/roman.js
> +}
Нет пустой строки в конце файла. Что может пойти не так: https://stackoverflow.com/a/729795/7844750

2021-02-11 22:32 UTC, paulnopaul commented
Готово!

2021-02-12 11:03 UTC, Betchika99 requested changes
тебе нужно лучше разобраться в перебирающих методах массивов и строк

2021-02-12 11:03 UTC, Betchika99 commented on tests/roman.js
> +    }
этот тест не очень корректный. Смотри, если твоя функция сломается на 2998 значении, как ты узнаешь это? лучше писать тесты, где ты одно значение принимаешь на вход и одно значение ожидаешь на выходе

2021-02-12 11:03 UTC, Betchika99 commented on source/roman.js
> + * @param {string} num - строка с числом
не хватает @return

2021-02-12 11:03 UTC, Betchika99 commented on source/roman.js
> +  }
нужно использовать методы массивов и строк, встроенные в js

2021-02-12 11:03 UTC, Betchika99 commented on source/roman.js
> +  }
здесь также нужно использовать встроенные методы массивов и строк

2021-02-12 20:33 UTC, paulnopaul commented
Готово!

2021-02-13 13:19 UTC, closed without merging