Лабзунова Дарья, вариант 16
frontend-park-mail-ru/homework_2021_1 pull request #39
Opened 2021-02-10 09:45 UTC by labzunova

2021-02-10 15:46 UTC, Sarafa2n reviewed
Привет и добро пожаловать на курс фронтенда! Тебя ждет увлекательное погружение в мир фронтенда. И желаю тебе удачи!
Ты хорошо справился с заданием, но есть некоторые замечания по коду. Думаю ты легко сможешь с ними справишься, если будут вопросы можешь спрашивать)

Ниже я описал конкретные недочеты, но есть одно большое, это стиль кода.
Давай поменяем на одно из-этого:
- Google: https://google.github.io/styleguide/jsguide.html
- AirBnd: https://github.com/airbnb/javascript

2021-02-10 15:46 UTC, Sarafa2n commented on source/format.js
> +const format = function (numbers, cols)
1 Давай заменим на стрелочную функцию. Почитать можно тут: https://learn.javascript.ru/arrow-functions-basics
2 Давай добавим JSDoc, так будет легче другим людям понять что делает данная функция.
3 Давай добавим `use strict`. Зачем это нужно можно почитать вот тут: https://learn.javascript.ru/strict-mode

2021-02-10 15:46 UTC, Sarafa2n commented on source/format.js
> +		return formated;
Целесообразнее это переделать на `reduce` Почитать вот тут: https://learn.javascript.ru/array-iteration

2021-02-10 15:46 UTC, Sarafa2n commented on source/format.js
> +			num = numbers[numbers.length - i - 1];
лучше не объявлять переменную без `let` или `const`

2021-02-10 15:46 UTC, Sarafa2n commented on source/format.js
> +		}
давай заменим на `map`

2021-02-10 15:46 UTC, Sarafa2n commented on source/format.js
> +		return 'wrong input';
Можно заменить на `throw`

2021-02-10 15:52 UTC, Sarafa2n commented
Добавь больше тестов еще)

2021-02-11 20:02 UTC, labzunova commented on source/format.js
> +		}
А мапу можно тут прикрутить? Я про нее в js почитала сейчас и показалось, что обязательно по всему массиву проходиться, что мне не надо. К тому же я кладу результаты в массив не последовательно, а вот с таким индексом (numbers.length - i - 1)%cols

2021-02-11 21:34 UTC, Sarafa2n requested changes
Посмотрел, отписал по решению, если будут вопросы или не поймешь как сделать пиши, объясню

2021-02-11 21:34 UTC, Sarafa2n commented on source/format.js
> +
Не нужен `else`, ведь в `if` `throw`.

2021-02-11 21:34 UTC, Sarafa2n commented on source/format.js
> +		for(let i = 0; i < cols; i++) { // определяем ширину каждой колонки
Пробел потерялся

2021-02-11 21:34 UTC, Sarafa2n commented on source/format.js
> +		let colsWidth =[];
`const` для неизменяемых объектов

2021-02-11 21:34 UTC, Sarafa2n commented on source/format.js
> +			let num = numbers[numbers.length - i - 1];
`const` для неизменяемых объектов

2021-02-11 21:34 UTC, Sarafa2n commented on source/format.js
> +			colsWidth[(numbers.length - i - 1)%cols] = (num + '').length;
1 Можно просто `const column = i % cols`
2 Ты все время приводишь число к строке, резоннее перевести числа в строку через `map`
3 Твое решение не будет работать если самое большое число в колонне не последнее, рекомендую использовать `Math.max()`

2021-02-11 21:34 UTC, Sarafa2n commented on source/format.js
> +		return formated;
Можно сразу сделать `return numbers.reduce`

2021-02-11 21:34 UTC, Sarafa2n commented on source/format.js
> +			}
1 очень не понятные вычисления, лучше всякие такие вещи выносить в отдельные переменные. (номер колонки, ширина колонки, длина числа) Также можно узнать является ли число последним и последняя ли колонка.
2 получить кол-во пробелов можно намного проще, просто вычесть из ширины колонки длину числа, и не нужны будут такие сложные `if`

2021-02-11 21:34 UTC, Sarafa2n commented on source/format.js
> +				nSpaces += ' ';
в JS есть такая функция как `repeat`. Почитать тут: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/repeat
И не нужен будет цикл

2021-02-12 08:51 UTC, Sarafa2n commented on source/format.js
> +		}
да, мапу здесь нет смысла использовать, можно обойтись просто `for` подробнее описал ниже

2021-02-12 10:16 UTC, labzunova commented on source/format.js
> +		let colsWidth =[];
так я же массив colsWidth меняю в следующих строчках

2021-02-12 10:37 UTC, Sarafa2n commented on source/format.js
> +		let colsWidth =[];
`colsWidth` это ссылка на массив

2021-02-12 10:43 UTC, Sarafa2n commented on source/format.js
> +		let colsWidth =[];
и пробел потерян, старайся работать глазами как линтер)

2021-02-12 11:28 UTC, Sarafa2n commented
А зачем ты делаешь `resolve` без `push` кода ?  
 Давай договоримся, что комментарии буду закрывать я.

2021-02-12 12:23 UTC, labzunova commented on source/format.js
> +			colsWidth[(numbers.length - i - 1)%cols] = (num + '').length;
Исправила сейчас код, но единственное чего не поняла - как мне в вычисление ширины каждой колонки прикрутить map? Я же должна изменять значения в массиве colsWidth каждый раз, когда нахожу число больше, а return в методе map добавляет в формируемый массив каждый раз новую ячейку.
Или вы тут имели в виду, что просто нужно перед циклом вычисления пройтись map-ом и превратить все в строки?
И сори что делала resolve раньше вас, просто раньше когда мне ревьюили код, я всегда решала проблему и нажимала resolve сама, не знала, что нужно так)

2021-02-12 12:28 UTC, Sarafa2n requested changes
Пожалуйста не закрывай комментарии, если тебе нужно это для себя, чтобы понять что ты сделала это, просто пиши в него _поправила_.
Как минимум закрывать комментарий без обновленного кода странно

2021-02-12 12:28 UTC, Sarafa2n commented on source/format.js
> +		colsWidth[i % cols] =  Math.max((numbers[i] + '').length, colsWidth[i % cols]);
1 давай всякие магические вычисления в отдельную переменную
2 `(numbers[i] + '').length` это очень страшно, во первых есть метод `toString()` и во вторых если ты везде приводишь число в строку просто мапой пробегись по `numbers` и переведи сразу все в строку

2021-02-12 12:28 UTC, Sarafa2n commented on source/format.js
> +	for(let i = 0; i < numbers.length; i++) {
Пробел потерян между `for` и `(`

2021-02-12 12:28 UTC, Sarafa2n commented on source/format.js
> +	const colsWidth = Array(cols).fill(0); // определяем ширину каждой колонки
Так тоже можно, но лучше `[]`

2021-02-12 12:28 UTC, Sarafa2n commented on source/format.js
> +		nSpaces = nSpaces.repeat(n);
можно в одну строку и  это `const`

2021-02-12 12:28 UTC, Sarafa2n commented on source/format.js
> +		let n;
Можешь пожалуйста называть переменные понятными словами

2021-02-12 12:28 UTC, Sarafa2n commented on source/format.js
> +		}
зачем ты делаешь `n++`?

2021-02-12 12:28 UTC, Sarafa2n commented on source/format.js
> +		let column = i % cols; // определяем, из какой колонки число
Неизменяемые переменные объявлять лучше через `const`

2021-02-12 12:35 UTC, Sarafa2n commented on source/format.js
> +			colsWidth[(numbers.length - i - 1)%cols] = (num + '').length;
Можно на ты, так будет удобнее. 
Смотри я отписал, что можно оставить `for` для ширины, и да имелось в виду, что надо мапой пройтись по `numbers` и превратить числа в строки, просто ты везде это делаешь, так лучше 1 раз чем постоянно, и я ниже отписал по поводу твоего "превращения в строку" ))
Насчет `resolve`, отписал ниже

2021-02-12 12:43 UTC, labzunova commented on source/format.js
> +	const colsWidth = Array(cols).fill(0); // определяем ширину каждой колонки
но мне же нужно инициализировать массив нулями, чтобы потом использовать Math.max() к нему

2021-02-12 12:46 UTC, Sarafa2n commented on source/format.js
> +	const colsWidth = Array(cols).fill(0); // определяем ширину каждой колонки
`Math.max(columnSizes[i % cols] || 0, numbers[i].length);`

2021-02-12 12:46 UTC, Sarafa2n commented on source/format.js
> +	const colsWidth = Array(cols).fill(0); // определяем ширину каждой колонки
тогда инициализация нулями не нужна)

2021-02-12 12:47 UTC, labzunova commented on source/format.js
> +		}
потому что если колонка не первая, то между ней и предыдущей должен быть плюс один пробел, чтобы не слипались колонки

2021-02-12 12:49 UTC, labzunova commented on source/format.js
> +			colsWidth[(numbers.length - i - 1)%cols] = (num + '').length;
окей, поняла, сделала!

2021-02-12 13:02 UTC, Sarafa2n requested changes

2021-02-12 13:02 UTC, Sarafa2n commented on source/format.js
> +};
Нет пустой строки в конце файла. Что может пойти не так: https://stackoverflow.com/a/729795/7844750

2021-02-12 13:12 UTC, labzunova commented on source/format.js
> +		if ((column === cols - 1) && (i != numbers.length - 1)) { //если колонка последняя
Если колонка последняя - ставим новую строчку(первое условие). Но в самом конце новая строчка по условию не ставится(второе условие).

2021-02-12 13:14 UTC, labzunova commented on source/format.js
> +		if ((column === cols - 1) && (i != numbers.length - 1)) { //если колонка последняя
Вынесу в отдельные переменные

2021-02-12 13:41 UTC, Sarafa2n commented on source/format.js
> +		spacesCount = colsWidth[column] - number.length;
а давай тут `const spacesCount`

2021-02-12 13:45 UTC, Sarafa2n commented on source/format.js
> +		let spacesCount = colsWidth[column] - number.length;
`const`

2021-02-13 18:21 UTC, closed without merging