Наказной Никита Вар3
frontend-park-mail-ru/homework_2021_1 pull request #41
Opened 2021-02-10 11:56 UTC by nicknaks

2021-02-12 14:29 UTC, Sarafa2n requested changes
Привет и добро пожаловать на курс фронтенда! Тебя ждет увлекательное погружение в мир фронтенда. И желаю тебе удачи!
Ты хорошо справился с заданием, но есть некоторые замечания по коду. Думаю ты легко сможешь с ними справишься, если будут вопросы можешь спрашивать)

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +};
Давай это вынесем в начало файла, и назовем `ROMAN_DIGITS`

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +}
Если я правильно понял, ты проверяешь строку на валидность, то эта функция вообще не нужна, можно сделать проверку регулярным выражением.

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +function fromArabicToRoman(number) {
Давай воспользуемся стрелочной функцией, и добавим JSDoc и сюда

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +  if (number < 1) return '';
Так лучше не писать, даже если одна строка в `if`

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +  return result;
Давай переделаем на `reduce`
И можно использовать `Object.entries`

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +  return str.toUpperCase().split('').reduce(function (previousValue, currentItem, index, arr) {
стрелочную функцию давай использовать

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +function fromRomanToArabic(str) {
Давай воспользуемся стрелочной функцией, и добавим JSDoc и сюда

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +    }
Зачем так сложно, можно обойтись лишь текущим и след элементом

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +    }
Можно тернарник из этого сделать

2021-02-12 14:29 UTC, Sarafa2n commented on source/roman.js
> +    const firstDigit = romanDigits[arr[index]];
у тебя есть `currentItem` зачем `arr[index]`

2021-02-12 22:22 UTC, nicknaks commented on source/roman.js
> +  return null;
Немного не понял, у меня ж все условия return заканчивается, зачем добавлять ветки else?

2021-02-13 08:28 UTC, Sarafa2n commented on source/roman.js
> +  return null;
13 14 строка можно объединить в один `if`

2021-02-13 10:36 UTC, nicknaks commented on source/roman.js
> +}
ну вроде их добавил, но работаю с ними в первый раз, если можно как то их улучшить, напиши)

2021-02-13 11:05 UTC, Sarafa2n requested changes

2021-02-13 11:05 UTC, Sarafa2n commented on source/roman.js
> +  return result;
смысл в `reduce`  возвращать значение, а ты по сути используешь его для перебора.
Давай это исправим так, чтобы было вот так: `return Object.entries(ROMAN_DIGITS).reduce()`

2021-02-13 11:05 UTC, Sarafa2n commented on source/roman.js
> + * @param {string} str
давай добавим описание к `str` как это у функции `roman`

2021-02-13 11:05 UTC, Sarafa2n commented on tests/roman.js
> +	QUnit.test('roman правильно определяет инвалидные входные параметры', function (assert) {
добавь еще тесты, к примеру просто `undefined` `null` `new String()`

2021-02-13 11:17 UTC, Sarafa2n commented on source/roman.js
> +  if (typeof value === 'string' && !(/[^XIVLCDM]/i.test(value) || /\b(.)\1{4,}/i.test(value))) {
а зачем ты проверяешь 4 подряд одинаковых символа ?

2021-02-13 11:20 UTC, nicknaks commented on source/roman.js
> +  if (typeof value === 'string' && !(/[^XIVLCDM]/i.test(value) || /\b(.)\1{4,}/i.test(value))) {
флаг i - рассматривает буквы без учета регистра

ну 4 подряд проверяю, чтобы нельзя было перевести XXXXXX...

2021-02-13 21:32 UTC, closed without merging