ДЗ-0 Иван Люляев
frontend-park-mail-ru/homework_2021_1 pull request #43
Opened 2021-02-10 14:30 UTC by Penguin-Run

Присылаю дз-0 получается))

2021-02-10 17:28 UTC, gavroman commented
Привет! Добро пожаловать на крутейший курс фронтенда! Получается дз прислалось)). Напиши плиз в описании МРа как тебя зовут и из какой ты группы. Крутое решение, классно, что подрубил либу. Отпишу пару мелких замечаний:
1) Внешняя либа - это конечно круто, но давай попробуем обойтись без нее, в этом случае это не так сложно)
2) Предлагаю попробовать заюзать современные и модные [стрелочные функции](https://learn.javascript.ru/arrow-functions-basics)
3) Для того чтобы код был понятен всем читающим принято писать [JSDoc коменты](https://devhints.io/jsdoc), давай потренируемся
4) Так как JS не типизированный язык, в твою функцию может прилететь все что угодно, го добавим проверок на невалидные входные данные разных типов и тестов на это дело

2021-02-10 17:29 UTC, gavroman commented on index.html
> +	console.log("running..");
стартует оно точно, го уберем)

2021-02-10 17:31 UTC, gavroman commented on source/solve.js
> +  let res = math.evaluate(str.replaceAll("x", x.toString(), str))
1) В JS уважают одинарные кавычки, го поменяем, тем более что в других местах `'`
2) Потерялась `;`
3) Почему `let`, а не `const`?

2021-02-10 18:45 UTC, Penguin-Run commented
Принял, спасибо за фидбек. Решил подключить стороннюю либу, так как самому норм решение в голову не пришло, а в интернете нашел метод рекурсивного спуска с большим количеством кода и прочие методы, с не самой простой реализацией. Не мог бы ты дать наводку какое здесь может быть оптимальное решение, как бы ты сделал?

2021-02-10 19:06 UTC, gavroman commented
> Принял, спасибо за фидбек. Решил подключить стороннюю либу, так как самому норм решение в голову не пришло, а в интернете нашел метод рекурсивного спуска с большим количеством кода и прочие методы, с не самой простой реализацией. Не мог бы ты дать наводку какое здесь может быть оптимальное решение, как бы ты сделал?

Есть несколько вариантов:
1) В лоб, рачками парсим строку, как-то что-то считаем, польская нотация и т. д. 
2) Почти как твое решение, только нативно - `eval`
3) Использовать конструктор функции, не функцию-конструктор, а именно конструктор функции

У каждого способа есть свои минусы, и раз я подсказал, предлагаю найти парочку отличий 2 и 3, а еще было бы интересно узнать чем 2 отличается от функции лыбы из твоего решения. Если сильно нагрузил и все сложнонепонятно, пиши в тг @gavroman ))

2021-02-10 20:49 UTC, Penguin-Run commented on index.html
> +	console.log("running..");
+

2021-02-10 20:49 UTC, Penguin-Run commented on source/solve.js
> +  let res = math.evaluate(str.replaceAll("x", x.toString(), str))
+

2021-02-10 21:15 UTC, Penguin-Run commented
Все правки сделал. Решение заменил на eval()

2021-02-10 21:18 UTC, gavroman commented
> Все правки сделал. Решение заменил на eval()

Так а в чем разница? Чем отличается eval от new Function() и от функции из той либы?

2021-02-10 21:31 UTC, Penguin-Run commented
Функция из той либы под капотом, судя по всему, имеет мощный парсер, заточенный именно под математику, может делать вещи вплоть до math.evaluate('2 inch to cm') например.
eval - функция, позволяющая динамически выполнять любую кусок js кода, что очень гибко, но и небезопасно. Просто в данном случае используется для подсчета арифметики.

2021-02-11 09:57 UTC, gavroman commented
огонь, ставлю апрув

2021-02-13 13:55 UTC, Drujininii requested changes

2021-02-13 13:55 UTC, Drujininii commented on source/solve.js
> +  const res = eval(str.replaceAll('x', x.toString(), str));
давай перепишем без eval

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

![image](https://user-images.githubusercontent.com/22628783/107851579-21caa380-6e1c-11eb-873a-6d9f4d3a25ec.png)

2021-02-17 11:02 UTC, closed without merging

2021-02-17 11:03 UTC, StealthTech commented
Закрыл по решению студента