Шишкин Сергей, вариант 10
frontend-park-mail-ru/homework_2021_1 pull request #48
Opened 2021-02-10 16:03 UTC by Sergei39

2021-02-11 22:45 UTC, yletamitlu reviewed
Привет, поздравляю с переводом во второй семестр, теперь тебе доступен увлекательный мир фронтенда :) Добро пожаловать в первую домашку на этом курсе, я буду ее у тебя проверять, если будут вопросы - пиши

2021-02-11 22:45 UTC, yletamitlu commented on source/letters.js
> +            if (arr[i] == arr[j]) {
Здесь лучше использовать '===', чтобы не было неявного преобразования типов

2021-02-11 22:45 UTC, yletamitlu commented on source/letters.js
> +const letters = function (str, format) {
А что, если входные данные окажутся не строкой? Нужно сделать проверку

2021-02-11 22:45 UTC, yletamitlu commented on source/letters.js
> +    else {
Если перед else в if/(else if) были return, то последний else излишен

2021-02-11 22:45 UTC, yletamitlu commented on source/letters.js
> +    return uniqArr(str.split('')).join('');
Здесь и на 39 строке можно не заморачиваться с дополнительной функцией, возвращающей массив уникальных символов, здесь можно использовать множество (https://learn.javascript.ru/map-set#set)
Кстати, наверное, выносить одну строку в отдельную функцию не то чтобы очень нужно, возможно, читаемость кода повысится, если флаг format в letters переименовать в что-то более понятное

2021-02-11 22:45 UTC, yletamitlu commented on source/letters.js
> +const removeDoubleElem = function (str) {
Какая симпатичная сиплюсплюсная функция, ну зато читаемая :)

2021-02-11 22:45 UTC, yletamitlu commented on source/letters.js
> +    let result = [];
Там, где можно использовать const, лучше использовать const

2021-02-11 22:45 UTC, yletamitlu commented on source/letters.js
> +    let arr = str.split('');
Там, где можно использовать const, лучше использовать const (2)

2021-02-13 23:43 UTC, Sergei39 commented
Привет, вроде поправил все, и у меня еще такой вопрос, а стрелочные функции лучше использовать когда функции небольшие, однострочные или в моем случае это тоже будет уместно?

2021-02-14 14:01 UTC, yletamitlu commented on source/letters.js
> +    if (letters === true) {
Можно еще улучшить это место - сделать после проверки на пришедший тип проверку флага letters на undefined с return внутри
Ну а дальше просто if (letters) {} else {}
Чтобы не было else if

2021-02-14 14:01 UTC, yletamitlu commented on source/letters.js
> +const removeDoubleElem = function (str) {
Есть какие-то идеи, как сделать эту функцию из си-шной в более js-вскую?

2021-02-15 05:45 UTC, Sergei39 commented on source/letters.js
> +const letters = function (str, letters) {
вроде понял, спасибо

2021-02-15 08:56 UTC, yletamitlu commented on source/letters.js
> +const remove = (str) => {
Давай все таки попробуем сделать js-ной эту функцию
Например, можешь использовать следующие методы:
1) filter (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)
2) indexOf (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf)
3) lastIndexOf (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf)

Можно додумать верную проверку для filter и тогда функция превратится в несколько строк :)

2021-02-15 10:24 UTC, Sergei39 commented on source/letters.js
> +const remove = (str) => {
Извиняюсь, не до конца понимал что надо было сделать)

2021-02-15 10:26 UTC, yletamitlu commented on source/letters.js
> +const remove = (str) => {
Зато теперь получилось супер :) Ну, мне нравится

2021-02-16 20:10 UTC, StealthTech requested changes

2021-02-16 20:10 UTC, StealthTech commented on source/letters.js
> +    if (typeof type === 'undefined') {
Здесь можно undefined

2021-02-16 20:10 UTC, StealthTech commented on source/letters.js
> +    if (type === true) {
т.к. у тебя всего три возможных значения для type — это true, false и undefined, а undefined ты проверяешь выше, тут можно просто `if (type)`. Выше стоит добавить такую же проверку, как для `str`, чтобы кидало исключение, если неправильный параметр

2021-02-16 20:10 UTC, StealthTech commented on source/letters.js
> +    else {
Справедливый комментарий, не учтен

2021-02-16 20:10 UTC, StealthTech commented on tests/letters.js
> +			TypeError('wrong input');
Кажется, перенос строки лишний

2021-02-16 20:10 UTC, StealthTech commented on tests/letters.js
> +	QUnit.test('Правильно работает с некорректными данными', function (assert) {
Не хватает теста на некорректные данные во втором параметре

2021-02-17 10:05 UTC, closed without merging