Add completed task 0
frontend-park-mail-ru/homework_2021_1 pull request #8
Opened 2021-02-07 12:13 UTC by timoninas

Антон Тимонин, АПО-21, Вариант 2

2021-02-07 12:19 UTC, Sarafa2n commented
Привет и добро пожаловать на курс фронтенда! Тебя ждет увлекательное погружение в мир фронтенда. И желаю тебе удачи!

2021-02-07 12:28 UTC, timoninas commented
> Привет и добро пожаловать на курс фронтенда! Тебя ждет увлекательное погружение в мир фронтенда. И желаю тебе удачи!

Спасибо! Буду стараться)

2021-02-07 12:59 UTC, Sarafa2n reviewed
Ты хорошо справился с дз0, но есть некоторые замечания по коду. 
Круто что ты сделал через рекурсию, но давай переделаем без нее, будет круто если получится сделать [чистую функцию](https://habr.com/ru/post/437512/)
И я не увидел твоих тестов на эту функцию, давай добавим их. И сделай проверку на данные, а вдруг они будут невалидные ?

2021-02-07 12:59 UTC, Sarafa2n commented on source/euclid.js
> +'use strict';
Круто что юзаешь `use strict`, можешь рассказать зачем это нужно?

2021-02-07 12:59 UTC, Sarafa2n commented on source/euclid.js
> +const euclid = function(...numbers) {
1 Круто что юзаешь rest оператор.
2 Давай сделаем [стрелочную функцию](https://learn.javascript.ru/arrow-functions-basics)
3 Давай добавим [JSDoc](https://jsdoc.app/) ведь ты же будешь работать в команде, и другим людям нужно будет как-то понять зачем эта функция нужна

2021-02-07 12:59 UTC, Sarafa2n commented on source/euclid.js
> +}
Нету пустой строки в конце файла. Что может пойти не так: https://stackoverflow.com/a/729795/7844750

2021-02-07 12:59 UTC, Sarafa2n commented on source/euclid.js
> +        }
В JS есть другие способы перебора массива: https://learn.javascript.ru/array-methods
Давай переделаем с использованием одного из методов, Например можно взять forEach

2021-02-08 07:42 UTC, timoninas commented on source/euclid.js
> +'use strict';
Указание коду, чтобы он работал в строгом режиме или говорят, что весь сценарий работает в современном режим.

Пока, с чем встретился - без 'use strict' можно объявлять переменные без 'let'. А в строгом режиме скрипт не запустится

2021-02-08 07:43 UTC, timoninas commented on source/euclid.js
> +const euclid = function(...numbers) {
👌

2021-02-08 07:43 UTC, timoninas commented on source/euclid.js
> +        }
Переделал с 'forEach'

2021-02-08 07:44 UTC, timoninas commented
Не знаю, правильно ли я проверку оформил. Так как мог сделать это внутри в алгоритма, но, кажется, что целостность нарушается: работа алгоритма в перемешку с проверкой

2021-02-08 13:50 UTC, Betchika99 requested changes

2021-02-08 13:50 UTC, Betchika99 commented on source/euclid.js
> +}
давай поправим названия переменных. Переменные должно сразу говорить об их назначении и в идеале не быть сокращениями. Это важно, чтобы другой программист, читающий твой код, мог без лишних телодвижений понять его смысл

2021-02-08 13:50 UTC, Betchika99 commented on source/euclid.js
> +        } else {
внутренний `else` здесь выглядит очень сложно. давай немного модернизируем конструкцию.
1) вынеси `res = array[0]` на строчку 21-22, т.е. вне цикла
2) в `if (index === 0)` сделай ретурн - так ты быстро перейдешь к следующему элементу массива
в таком варианте код из блока `else` не будет обернут в такую вложенность и будет выглядеть более красиво

2021-02-10 22:17 UTC, closed without merging